<?php
// $Id: pnadmin.php 217 2009-11-12 17:06:36Z herr.vorragend $
// ----------------------------------------------------------------------
// LICENSE
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License (GPL)
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// To read the license please visit http://www.gnu.org/copyleft/gpl.html
// ----------------------------------------------------------------------

/**
 * main function
 *
 */
function bbcode_admin_main()
{
    if (!SecurityUtil::checkPermission('bbcode::', "::", ACCESS_ADMIN)) {
        return LogUtil::registerPermissionError(pnConfigGetVar('entrypoint', 'index.php'));
    }

    $hmods = pnModAPIFunc('modules', 'admin', 'gethookedmodules', array('hookmodname' => 'bbcode'));
    foreach($hmods as $hmod => $dummy) {
        $modid = pnModGetIDFromName($hmod);
        $moddata = pnModGetInfo($modid);
        $moddata['id'] = $modid;
        $hookedmodules[] = $moddata;
    }

    $pnr = pnRender::getInstance('bbcode', false, null, true);
    $pnr->assign('hookedmodules', $hookedmodules);
    return $pnr->fetch('bbcode_admin_main.html');
}

/**
 * configuration
 *
 */
function bbcode_admin_config()
{
    if (!SecurityUtil::checkPermission('bbcode::', "::", ACCESS_ADMIN)) {
        return LogUtil::registerPermissionError(pnConfigGetVar('entrypoint', 'index.php'));
    }

    Loader::requireOnce('modules/bbcode/pnincludes/bbcode_admin_confighandler.class.php');

    // Create output object
    $pnf = FormUtil::newpnForm('bbcode');

    // Return the output that has been generated by this function
    return $pnf->pnFormExecute('bbcode_admin_config.html', new bbcode_admin_confighandler());
}
