<?php
$schools = Array(
'centre-5' => Array(
'clientCode' => '08000005',
'type' => '11',
'url_type' => 'standard',
'url_host' => '',
'id_nodes' => '5',
'dbhost_nodes' => 'localhost',
'database_nodes' => '',
'diskPercent_nodes' => '0',
),
'usu5' => Array(
'new_dns' => 'centre-5',
),
'centre-6' => Array(
'clientCode' => '08000006',
'type' => '8',
'url_type' => 'standard',
'url_host' => '',
'id_nodes' => '6',
'dbhost_nodes' => 'localhost',
'database_nodes' => '',
'diskPercent_nodes' => '1',
),
'usu6' => Array(
'new_dns' => 'centre-6',
),
'centre-7' => Array(
'clientCode' => '08000007',
'type' => '7',
'url_type' => 'standard',
'url_host' => '',
'id_nodes' => '7',
'dbhost_nodes' => 'localhost',
'database_nodes' => '',
'diskPercent_nodes' => '1',
),
'usu7' => Array(
'new_dns' => 'centre-7',
),
'centre-8' => Array(
'clientCode' => '08000008',
'type' => '5',
'url_type' => 'standard',
'url_host' => '',
'id_nodes' => '8',
'dbhost_nodes' => 'localhost',
'database_nodes' => '',
'diskPercent_nodes' => '1',
),
'usu8' => Array(
'new_dns' => 'centre-8',
),
'usu1' => Array(
'clientCode' => '08000001',
'type' => '1',
'url_type' => 'standard',
'url_host' => '',
'id_moodle2' => '1',
'dbhost_moodle2' => '',
'database_moodle2' => 'XE',
'diskPercent_moodle2' => '5',
'id_nodes' => '1',
'dbhost_nodes' => 'localhost',
'database_nodes' => '',
'diskPercent_nodes' => '0',
'id_intranet' => '1',
'dbhost_intranet' => 'localhost',
'database_intranet' => '',
'diskPercent_intranet' => '0',
),
'usu2' => Array(
'clientCode' => '08000002',
'type' => '2',
'url_type' => 'standard',
'url_host' => '',
'id_moodle2' => '2',
'dbhost_moodle2' => '',
'database_moodle2' => 'XE',
'diskPercent_moodle2' => '2',
'id_nodes' => '2',
'dbhost_nodes' => 'localhost',
'database_nodes' => '',
'diskPercent_nodes' => '0',
'id_intranet' => '2',
'dbhost_intranet' => 'localhost',
'database_intranet' => '',
'diskPercent_intranet' => '0',
),
'usu3' => Array(
'clientCode' => '08000003',
'type' => '4',
'url_type' => 'standard',
'url_host' => '',
'id_moodle2' => '3',
'dbhost_moodle2' => '',
'database_moodle2' => 'XE',
'diskPercent_moodle2' => '2',
'id_nodes' => '3',
'dbhost_nodes' => 'localhost',
'database_nodes' => '',
'diskPercent_nodes' => '0',
),
'usu4' => Array(
'clientCode' => '08000004',
'type' => '6',
'url_type' => 'standard',
'url_host' => '',
'id_nodes' => '4',
'dbhost_nodes' => 'localhost',
'database_nodes' => '',
'diskPercent_nodes' => '1',
'id_moodle2' => '4',
'dbhost_moodle2' => '',
'database_moodle2' => 'XE',
'diskPercent_moodle2' => '2',
),
);
