<?php
/**
 * Zikula Application Framework
 * @copyright  (c) Zikula Development Team
 * @license    GNU/GPL
 * @category   Zikula_3rdParty_Modules
 * @package    Content_Management
 * @subpackage Quotes
*/

class Quotes_Controller_Admin extends Zikula_AbstractController
{
    /**
     * Quotes main administration function
     * @author The Zikula Development Team
     * @return string HTML string
     */
    public function main()
    {
        // security check
        if (!SecurityUtil::checkPermission('Quotes::', '::', ACCESS_EDIT)) {
            return LogUtil::registerPermissionError();
        }

        $this->view->setCaching(false);        

        // return the output that has been generated by this function
        return $this->view->fetch('quotes_admin_main.tpl');
    }

    /**
     * Display form to create a new quote
     * @author The Zikula Development Team
     * @return string HTML string
     */
    public function newitem()
    {
        // security check
        if (!SecurityUtil::checkPermission('Quotes::', '::', ACCESS_ADD)) {
            return LogUtil::registerPermissionError();
        }

        // get all module vars
        $modvars = ModUtil::getVar($this->name);

        $this->view->setCaching(false);

        if ($modvars['enablecategorization']) {
            $catregistry = CategoryRegistryUtil::getRegisteredModuleCategories($this->name, 'quotes');
            $this->view->assign('catregistry', $catregistry);
        }
		$this->view->assign('status', 1);

        // assign the module vars
        $this->view->assign($modvars);

        return $this->view->fetch('quotes_admin_new.tpl');
    }

    /**
     * Display full list of quotes
     * @author The Zikula Development Team
     * @return string HTML string
     */
    public function view($args)
    {
        // security check
        if (!(SecurityUtil::checkPermission('Quotes::', '::', ACCESS_READ))) {
            return LogUtil::registerPermissionError();
        }

        // Get parameters from whatever input we need.
        $startnum = FormUtil::getPassedValue('startnum', isset($args['startnum']) ? $args['startnum'] : null, 'GET');
        $keyword  = FormUtil::getPassedValue('quotes_keyword', isset($args['quotes_keyword']) ? $args['quotes_keyword'] : '', 'POST');
        $keyword_GET  = FormUtil::getPassedValue('keyword', isset($args['keyword']) ? $args['keyword'] : '', 'GET');
		if ($keyword_GET) $keyword = $keyword_GET;
        $author   = FormUtil::getPassedValue('quotes_author', isset($args['quotes_author']) ? $args['quotes_author'] : '', 'POST');
        $author_GET  = FormUtil::getPassedValue('author', isset($args['author']) ? $args['author'] : '', 'GET');
		if ($author_GET) $author = $author_GET;
        $property = FormUtil::getPassedValue('quotes_property', isset($args['quotes_property']) ? $args['quotes_property'] : null, 'POST');
        $property_GET = FormUtil::getPassedValue("property", isset($args["property"]) ? $args["property"] : null, 'GET');
		if ($property_GET) $property = $property_GET;
        $category = FormUtil::getPassedValue("quotes_{$property}_category", isset($args["quotes_{$property}_category"]) ? $args["quotes_{$property}_category"] : null, 'POST');
        $category_GET = FormUtil::getPassedValue("category", isset($args["category"]) ? $args["category"] : null, 'GET');
		if ($category_GET) $category = $category_GET;
        $clear    = FormUtil::getPassedValue('clear', false, 'POST');
        if ($clear) {
            $property = $category = $keyword = $author = null;
        }
        $sort = FormUtil::getPassedValue('sort', $sort, 'GET');
        $sortdir = FormUtil::getPassedValue('sortdir', $sortdir, 'GET');
        if ($sortdir != 'ASC' && $sortdir != 'DESC') {
                $sortdir = 'ASC';
        }

        // get all module vars
        $modvars = ModUtil::getVar($this->name);

        if ($modvars['enablecategorization']) {
            $catregistry  = CategoryRegistryUtil::getRegisteredModuleCategories($this->name, 'quotes');
            $properties = array_keys($catregistry);

            // validate and build the category filter - mateo
            if (!empty($property) && in_array($property, $properties) && !empty($category)) {
                $catFilter = array($property => $category);
            }

            // assign a default property - mateo
            if (empty($property) || !in_array($property, $properties)) {
                $property = $properties[0];
            }

            // plan ahead for ML features
            $propArray = array();
            foreach ($properties as $prop) {
                $propArray[$prop] = $prop;
            }
        }
		
		$filter = array('startnum' => $startnum, 'sort' => $sort, 'sortdir' => $sortdir,
                'numitems' => $modvars['itemsperpage'],
                'keyword'  => $keyword,
                'author'   => $author,
                'category' => isset($catFilter) ? $catFilter : null,
                'catregistry'  => isset($catregistry) ? $catregistry : null);

        // get the matching quotes
        $quotes = ModUtil::apiFunc($this->name, 'user', 'getall', $filter);

        $items = array();
        foreach ($quotes as $key => $quote)
        {
            // options for the item
            $options = array();
            if (SecurityUtil::checkPermission('Quotes::', $quote['author']."::".$quote['qid'], ACCESS_EDIT)) {
                $quotes[$key]['options'][] = array('url'   => ModUtil::url($this->name, 'admin', 'modify', array('qid' => $quote['qid'])),
                        'image' => 'xedit.gif',
                        'title' => $this->__('Edit'));

                if (SecurityUtil::checkPermission('Quotes::', $quote['author']."::".$quote['qid'], ACCESS_DELETE)) {
                    $quotes[$key]['options'][] = array('url'   => ModUtil::url($this->name, 'admin', 'delete', array('qid' => $quote['qid'])),
                            'image' => '14_layer_deletelayer.gif',
                            'title' => $this->__('Delete'));
                }
            }
            $items[] = $quotes[$key];
        }

        $this->view->setCaching(false);

        // assign the default language
        $this->view->assign('lang', ZLanguage::getLanguageCode());

        // assign the items and modvars to the template
        $this->view->assign('quotes', $items);
        $this->view->assign($modvars);

        // add the current filters
        $this->view->assign('quotes_author', $author);
        $this->view->assign('quotes_keyword', $keyword);
        $this->view->assign('sort', $sort);
        $this->view->assign('sortdir', $sortdir);
		$this->view->assign('filter_active', (empty($author) && empty($keyword) && empty($category)) ? false : true);

        // assign the categories information if enabled
        if ($modvars['enablecategorization']) {
            $this->view->assign('catregistry', $catregistry);
            $this->view->assign('numproperties', count($propArray));
            $this->view->assign('properties', $propArray);
            $this->view->assign('property', $property);
            $this->view->assign("category", $category);
        }

        // assign the values for the smarty plugin to produce a pager
        $this->view->assign('pager', array('itemsperpage' => $modvars['itemsperpage'],
                'numitems' => ModUtil::apiFunc($this->name, 'user', 'countitems',
                array('keyword'  => $keyword,
                'author'   => $author,
                'category' => isset($catFilter) ? $catFilter : null))));

        return $this->view->fetch('quotes_admin_view.tpl');
    }

    /**
     * Edit quote
     * @author The Zikula Development Team
     * @param 'qid' Quote id to delete
     * @param 'qauther' Author of quote to delete
     * @param 'confirm' Delete confirmation
     * @return mixed HTML string if confirm is null, true otherwise
     */
    public function modify($args)
    {
        // get parameters from whatever input we need.
        $qid = FormUtil::getPassedValue('qid', isset($args['qid']) ? $args['qid'] : null, 'GET');
        $objectid = FormUtil::getPassedValue('objectid', isset($args['objectid']) ? $args['objectid'] : null, 'GET');

        // check to see if we have been passed $objectid, the generic item identifier.
        if (!empty($objectid)) {
            $qid = $objectid;
        }

        // get the quote
        $quote = ModUtil::apiFunc($this->name, 'user', 'get', array('qid' => $qid));
        if (!$quote) {
            return DataUtil::formatForDisplayHTML($this->__('No such Quote found.'));
        }

        // security check
        if (!SecurityUtil::checkPermission('Quotes::', "$quote[author]::$qid", ACCESS_EDIT)) {
            return LogUtil::registerPermissionError();
        }

        // get all module vars
        $modvars = ModUtil::getVar($this->name);

        if ($modvars['enablecategorization']) {
            // load the category registry util
            $catregistry = CategoryRegistryUtil::getRegisteredModuleCategories($this->name, 'quotes');

            $this->view->assign('catregistry', $catregistry);
        }

        // assign the item and module vars
        $this->view->assign($quote);
        $this->view->assign($modvars);

        // return the output that has been generated by this function
        return $this->view->fetch('quotes_admin_modify.tpl');
    }

    /**
     * Delete selected quote
     * @author The Zikula Development Team
     * @param 'qid' Quote id to delete
     * @param 'qauther' Author of quote to delete
     * @param 'confirm' Delete confirmation
     * @return mixed HTML string if confirm is null, true otherwise
     */
    public function delete($args)
    {
        // get parameters from whatever input we need.
        $qid = FormUtil::getPassedValue('qid', isset($args['qid']) ? $args['qid'] : null, 'GETPOST');
        $objectid = FormUtil::getPassedValue('objectid', isset($args['objectid']) ? $args['objectid'] : null, 'POST');
        $confirmation = FormUtil::getPassedValue('confirmation', null, 'POST');
        if (!empty($objectid)) {
            $qid = $objectid;
        }

        // get the quote
        $item = ModUtil::apiFunc($this->name, 'user', 'get', array('qid' => $qid));
        if ($item == false) {
            return LogUtil::registerError ($this->__('No such Quote found.'));
        }

        // security check
        if (!SecurityUtil::checkPermission('Quotes::', $item['author'].'::'.$qid, ACCESS_DELETE)) {
            return LogUtil::registerPermissionError();
        }

        // check for confirmation.
        if (empty($confirmation)) {
            // no confirmation yet - display a suitable form to obtain confirmation
            // of this action from the user

            $this->view->setCaching(false);

            // quote id
            $this->view->assign('qid', $qid);

            // return the output that has been generated by this function
            return $this->view->fetch('quotes_admin_delete.tpl');
        }

        // if we get here it means that the user has confirmed the action

        // Confirm the forms authorisation key
        $this->checkCsrfToken();

        // delete the quote
        if (ModUtil::apiFunc($this->name, 'admin', 'delete', array('qid' => $qid))) {
            LogUtil::registerStatus($this->__('Done! Quote deleted.'));
        }

        // This function generated no output, and so now it is complete we redirect
        // the user to an appropriate page for them to carry on their work
        return System::redirect(ModUtil::url($this->name, 'admin', 'view'));
    }

    /**
     * Search quote database by keyword - unfinished obviously.
     * @author The Zikula Development Team
     * @return string HTML string
     */
    public function modifyconfig()
    {
        // security check
        if (!SecurityUtil::checkPermission('Quotes::', '::', ACCESS_ADMIN)) {
            return LogUtil::registerPermissionError();
        }

        $this->view->setCaching(false);
        $this->view->assign(ModUtil::getVar($this->name));

        // return the output that has been generated by this function
        return $this->view->fetch('quotes_admin_modifyconfig.tpl');
    }

    /**
     * Create a new quote
     * @author The Zikula Development Team
     * @param 'qquote' quote text
     * @param 'qauthor' quote author
     * @return bool true if create success, false otherwise
     */
    public function create($args)
    {
        // Confirm the forms authorisation key
        $this->checkCsrfToken();

        // get parameters from whatever input we need.
        $quote = FormUtil::getPassedValue('quote', isset($args['quote']) ? $args['quote'] : null, 'POST');

        // notable by its absence there is no security check here.
        // create the quote
        $qid = ModUtil::apiFunc($this->name, 'admin', 'create', $quote);
        if ($qid != false) {
            // success
            LogUtil::registerStatus($this->__('Done! Quote created.'));
        }

        return System::redirect(ModUtil::url($this->name, 'admin', 'view'));
    }

    /**
     * Update quote
     *
     * Takes info from edit form and passes to API
     * @author The Zikula Development Team
     * @param 'qid' Quote id to delete
     * @param 'qauther' Author of quote to delete
     * @param 'confirm' Delete confirmation
     * @return mixed HTML string if confirm is null, true otherwise
     */
    public function update($args)
    {
        // Confirm the forms authorisation key
        $this->checkCsrfToken();

        // get parameters from whatever input we need.
        $quote = FormUtil::getPassedValue('quote', isset($args['quote']) ? $args['quote'] : null, 'POST');

        // check to see if we have been passed $objectid, the generic item identifier.
        if (!empty($quote['objectid'])) {
            $quote['qid'] = $quote['objectid'];
        }

        // notable by its absence there is no security check here.
        // update the quote
        if (ModUtil::apiFunc($this->name, 'admin', 'update', $quote)) {
            // success
            LogUtil::registerStatus($this->__('Done! Quote updated.'));
        }

        // this function generated no output, and so now it is complete we redirect
        // the user to an appropriate page for them to carry on their work
        return System::redirect(ModUtil::url($this->name, 'admin', 'view'));
    }

    /**
     * Update Quotes Config
     * @author The Zikula Development Team
     * @return string HTML string
     */
    public function updateconfig()
    {
        // Confirm the forms authorisation key
        $this->checkCsrfToken();
        // Security check
		 $this->throwForbiddenUnless(SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN));

        // update module variables.
        $modvars = array();
        $modvars['itemsperpage'] = FormUtil::getPassedValue('itemsperpage', 25, 'POST');
        $modvars['enablecategorization'] = (bool)FormUtil::getPassedValue('enablecategorization', false, 'POST');
		$this->setVars($modvars);

        // the module configuration has been updated successfuly
        LogUtil::registerStatus($this->__('Done! Module configuration updated.'));

        // this function generated no output, and so now it is complete we redirect
        // the user to an appropriate page for them to carry on their work
        return System::redirect(ModUtil::url($this->name, 'admin', 'view'));
    }
}