<?php
/**
 * Show the forums where the users can access
 * @author		Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @return		The list of forums where the users have access
 */
function iw_forums_user_main()
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	// security check
	if (!SecurityUtil::checkPermission('iw_forums::', "::", ACCESS_READ)) {
		return LogUtil::registerError(__('Sorry! No authorization to access this module.', $dom), 403);
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	$registres = pnModAPIFunc('iw_forums','user','getall', array('filter' => '1'));
	foreach ($registres as $registre) {
		$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $registre['fid']));
		$n_msg = pnModAPIFunc('iw_forums', 'user', 'compta_msg', array('fid' => $registre['fid'],
																		'tots' => true));
		$n_msg_no_llegits = $n_msg['nollegits'];
		$marcats = $n_msg['marcats'];
		$n_msg = $n_msg['nmsg'];
		$color_no_read = ($n_msg_no_llegits > 0) ? "red" : "black";
		$n_temes = pnModAPIFunc('iw_forums', 'user', 'compta_temes', array('fid' => $registre['fid']));
		$forums[] = array('fid' => $registre['fid'],
							'nom_forum' => $registre['nom_forum'],
							'descriu' => $registre['descriu'],
							'n_msg_no_llegits' => $n_msg_no_llegits,
							'n_msg' => $n_msg,
							'color_no_read' => $color_no_read,
							'n_temes' => $n_temes,
							'marcats' => $marcats,
							'access' => $access);	
	}
	$pnRender -> assign('forums', $forums);
	// count the new visit
	if (pnModAvailable('iw_visites') && pnModIsHooked('iw_visites', 'iw_forums')){
		// insert a record
		pnModAPIFunc('iw_visites', 'user', 'visita');
	} 
	// return the output that has been generated by this function
	return $pnRender -> fetch('iw_forums_user_main.htm');
}

/**
 * Show the module information
 * @author	Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @return	The module information
 */
function iw_forums_user_module()
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	// security check
	if (!SecurityUtil::checkPermission('iw_forums::', "::", ACCESS_READ)) {
		return LogUtil::registerError(__('Sorry! No authorization to access this module.', $dom), 403);
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	$module = pnModFunc('iw_main', 'user', 'module_info', array('module_name' => 'iw_forums',
																'type' => 'user'));
	$pnRender -> assign('module', $module);
	return $pnRender -> fetch('iw_forums_user_module.htm');
}

/**
 * Check the user access to a forum
 * @author:	Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	Identity of the forum
 * @return:	0 - No access
 *		1 - Read
 *		2 - Read and Write
 *		3 - Read, write and topics creation
 *		4 - Moderate
*/
function iw_forums_user_access($args)
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'POST');
	$uid = FormUtil::getPassedValue('uid', isset($args['uid']) ? $args['uid'] : pnUserGetVar('uid'), 'POST');
	$sv = FormUtil::getPassedValue('sv', isset($args['sv']) ? $args['sv'] : null, 'POST');
	if(!pnModFunc('iw_main', 'user', 'checkSecurityValue', array('sv' => $sv))){
		// security check
		if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
			return LogUtil::registerPermissionError();
		}
	}else{
		$requestByCron = true;
	}
	// needed argument
	if (!isset($fid) || !is_numeric($fid)) {
		return LogUtil::registerError (__('Error! Could not do what you wanted. Please check your input.', $dom));
	}
	// get item
	$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
	$item = pnModAPIFunc('iw_forums', 'user', 'get', array('fid' => $fid,
															'sv' => $sv));
	if ($item == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// if forum is not active deny access
	if($item['actiu'] != 1){
		return 0;
	}
	$uid = (!pnUserLoggedIn() && !$requestByCron) ? '-1': $uid;
	if($uid != '-1'){
		if($uid != pnUserGetVar('uid') && !$requestByCron){
			return 0;
		}
	}
	// check if the user can access the forum as moderator
	if(strpos($item['mod'], '$'.$uid.'$') !== false){
		return 4;
	}
	// if user is not registered check if can access the forum only in readtable mode
	if($uid == '-1' && strpos($item['grup'], '$-1|') !== false){
		return 1;
	}
	// check if user can access the forum throug the group
	// get user groups
	$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
	$groups = pnModFunc('iw_main', 'user', 'getAllUserGroups', array('sv' => $sv,
																		'uid' => $uid));
	$accessType = 0;
	foreach($groups as $group){
		$pos = strpos($item['grup'], '$'.$group['id'].'|');
		if($pos !== false){
			$access = substr($item['grup'], $pos + 1, strlen($group['id']) + 2);
			$accessArray = explode('|', $access);
			if($accessType < $accessArray[1]){
				$accessType = $accessArray[1];
			}
		}
	}
	return $accessType;
}

/**
 * Show the topics and the messages without topic into a forum
 * @author	Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	Identity of the forum
 * @return	The list of topics and messages without topic
 */
function iw_forums_user_forum($args)
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'REQUEST');
	$ftid = FormUtil::getPassedValue('ftid', isset($args['ftid']) ? $args['ftid'] : 0, 'POST');
	$inici = FormUtil::getPassedValue('inici', isset($args['inici']) ? $args['inici'] : 1, 'REQUEST');
	$u = FormUtil::getPassedValue('u', isset($args['u']) ? $args['u'] : 0, 'REQUEST');
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	//check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid));
	if($access < 1){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	// get the forum
	$registre = pnModAPIFunc('iw_forums', 'user', 'get', array('fid' => $fid));
	if ($registre == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get the topics of the forum
	$llistatemes = pnModAPIFunc('iw_forums', 'user', 'get_temes', array('fid' => $fid,
																		'u' => $u));
	if ($llistatemes != false) {
		$hi_ha_temes = true;
	}
	foreach($llistatemes as $tema){
		$usersList .= $tema['lastuser'].'$$'.$tema['usuari'].'$$';
	}
	// get list of messages into the topic
 	$listmessages = pnModAPIFunc('iw_forums', 'user', 'getall_msg', array('ftid' => 0,
																			'fid' => $registre['fid'],
																			'usuari' => $u,
																			'indent' => 0,
																			'idparent' => 0,
																			'inici' => $inici,
																			'rpp' => 10));
	if ($listmessages != false) {
		$hi_ha_missatges=true;
		foreach ($listmessages as $message) {
			$imatge = (strpos($message['llegit'],'$'.pnUserGetVar('uid').'$')==0) ? 'msgNo.gif' : 'msg.gif';
			$marcat = (strpos($message['marcat'],'$'.pnUserGetVar('uid').'$') == 0) ? 'res.gif' : 'marcat.gif';
			$m = (strpos($message['marcat'],'$'.pnUserGetVar('uid').'$') == 0) ? '1' : '0';
			$textmarca = (strpos($message['marcat'],'$'.pnUserGetVar('uid').'$') == 0) ? __("Check the message",$dom) : __('Uncheck the message', $dom);
			$temps_esborrat = $registre['msgDelTime'];
			$temps_edicio = $registre['msgEditTime'];
			$esborrable = (time() < $message['data'] + 60 * $temps_esborrat && $message['usuari'] == pnUserGetVar('uid')) ? true : false;
			$editable = (time() < $message['data'] + 60 * $temps_edicio && $message['usuari'] == pnUserGetVar('uid')) ? true : false;
			$messages[] = array('fmid' => $message['fmid'],
								'imatge' => $imatge,
								'title' => $message['titol'],
								'user' => $message['usuari'],
								'date' => date('d/m/y',$message['data']),
								'time' => date('H.i',$message['data']),
								'adjunt' => $message['adjunt'],
								'icon' => $message['icon'],
								'marcat' => $marcat,
								'm' => $m,
								'esborrable' => $esborrable,
								'editable' => $editable,
								'textmarca' => $textmarca,
								'indent' => $message['indent'],
								'oid' => $message['oid']);
		}
	}
	// set as visited
	if (pnModAvailable('iw_visits') && pnModIsHooked('iw_visits', 'iw_forums')){
		// set record
		pnModAPIFunc('iw_visits', 'user', 'visit');
	}
	if($access == 4){$moderator = true;}
	$adjunts = ($registre['adjunts'] == 1) ? true : false;
	(pnModAvailable('bbsmile') && pnModIsHooked('bbsmile', 'iw_forums')) ? $pnRender -> assign('icons', true) : $pnRender -> assign('icons', false);
	$total = pnModAPIFunc('iw_forums', 'user', 'compta_msg', array('ftid' => $ftid,
																	'fid' => $fid,
																	'u' => $u));
	$pager = pnModFunc('iw_forums', 'user', 'pager', array('inici' => $inici,
															'total' => $total['nparent'],
															'rpp' => 10,
															'urltemplate' => 'index.php?module=iw_forums&func=forum&inici=%%&fid=' . $fid . '&ftid=' . $ftid . '&u=' . $u));
	// get list of users who have writed into the forum
	$usuaris_rem = pnModAPIFunc('iw_forums', 'user', 'getremitents', array('ftid' => 0,
																			'fid' => $registre['fid']));
	foreach($usuaris_rem as $user){
		$usersList .= $user['usuari'].'$$';
	}	
	// get all users information
	$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
	$users = pnModFunc('iw_main', 'user', 'getAllUsersInfo', array('sv' => $sv,
																	'info' => 'ncc',
																	'list' => $usersList));
	$usuaris[] = array('id' => 0,
						'name' => __('Choose the sender...', $dom));
	foreach($usuaris_rem as $usuari_rem){
		if($users[$usuari_rem['usuari']] != ''){
			$usuaris[] = array('id' => $usuari_rem['usuari'],
								'name' => $users[$usuari_rem['usuari']]);
		}
	}
	$pnRender -> assign('users', $users);
	$pnRender -> assign('name', $registre['nom_forum']);
	$pnRender -> assign('adjunts', $adjunts);
	$pnRender -> assign('access', $access);
	$pnRender -> assign('hi_ha_temes', $hi_ha_temes);
	$pnRender -> assign('hi_ha_missatges', $hi_ha_missatges);
	$pnRender -> assign('temes', $llistatemes);
	$pnRender -> assign('moderator', $moderator);
	$pnRender -> assign('messages', $messages);
	$pnRender -> assign('usuaris', $usuaris);
	$pnRender -> assign('u', $u);
	$pnRender -> assign('fid', $fid);
	$pnRender -> assign('ftid', $ftid);
	$pnRender -> assign('pager', $pager);
	$pnRender -> assign('inici', $inici);
	return $pnRender -> fetch('iw_forums_user_forum.htm');
}

/**
 * Show a form for a topics creation
 * @author	Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	Identity of the forum, topic title, topic description and first msg information
 * @return	The list of topics and messages without topic
 */
function iw_forums_user_nou_tema($args){
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'REQUEST');
	$titol = FormUtil::getPassedValue('titol', isset($args['titol']) ? $args['titol'] : null, 'POST');
	$descriu = FormUtil::getPassedValue('descriu', isset($args['descriu']) ? $args['descriu'] : null, 'POST');
	$titolmsg = FormUtil::getPassedValue('titolmsg', isset($args['titolmsg']) ? $args['titolmsg'] : null, 'POST');
	$msg = FormUtil::getPassedValue('msg', isset($args['msg']) ? $args['msg'] : null, 'POST');
	$inici = FormUtil::getPassedValue('inici', isset($args['inici']) ? $args['inici'] : null, 'REQUEST');
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	// check if user can access the forum
	if(pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid)) < 3){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	// get forum information
	$registre = pnModAPIFunc('iw_forums', 'user', 'get', array('fid' => $fid));
	if ($registre == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	$pnRender -> assign('adjunts', $registre['adjunts']);
	$pnRender -> assign('inici', $inici);
	$pnRender -> assign('name', $registre['nom_forum']);
	$pnRender -> assign('fid', $fid);
	$pnRender -> assign('extensions', pnModGetVar('iw_main','extensions'));
	return $pnRender -> fetch('iw_forums_user_new_tema.htm');
}

/**
 * Create a new topic and message
 * @author	Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	Values for the topic and message
 * @return	Redirect user to forum init page
 */
function iw_forums_user_crear_tema($args){
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$titol = FormUtil::getPassedValue('titol', isset($args['titol']) ? $args['titol'] : null, 'POST');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'POST');
	$ftid = FormUtil::getPassedValue('ftid', isset($args['ftid']) ? $args['ftid'] : null, 'POST');
	$descriu = FormUtil::getPassedValue('descriu', isset($args['descriu']) ? $args['descriu'] : null, 'POST');
	$titolmsg = FormUtil::getPassedValue('titolmsg', isset($args['titolmsg']) ? $args['titolmsg'] : null, 'POST');
	$msg = FormUtil::getPassedValue('msg', isset($args['msg']) ? $args['msg'] : null, 'POST');
	$adjunt = FormUtil::getPassedValue('adjunt', isset($args['adjunt']) ? $args['adjunt'] : null, 'POST');
	$icon = FormUtil::getPassedValue('icon', isset($args['icon']) ? $args['icon'] : null, 'POST');
	$fileName = $_FILES['adjunt']['name'];
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	// confirm authorisation code
	if (!SecurityUtil::confirmAuthKey('iw_forums')) {
		return LogUtil::registerAuthidError (pnModURL('iw_forums', 'user', 'forum', array('fid' => $fid)));
	}
	// get forum information
	$registre = pnModAPIFunc('iw_forums', 'user', 'get', array('fid' => $fid));
	if ($registre == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid));
	if($access < 3){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// check if user can moderate the forum
	$moderator = ($access == 4) ? true : false;
	// create a new topic
	$lidTema = pnModAPIFunc('iw_forums', 'user', 'crear_tema', array('fid' => $fid,
																		'titol' => $titol,
																		'descriu' => $descriu));
	if($lidTema != false){
		$missatge = __('A new topic has been created.', $dom);
		if($registre['msgDelTime'] > 0 && !$moderator){
			$missatge .= '<br />'.__('During the next ', $dom).$registre['msgDelTime'].__(' minutes you can delete the topic.', $dom);
		}
		LogUtil::registerStatus ($missatge);
	}else{
		LogUtil::registerError (__('An error has occurred while creating a new topic', $dom));
	}
	// check the needed values
	$nom_fitxer =  (empty($fileName)) ? '' : $fileName;
	// update the attached file to the server
	if($fileName != ''){
		$folder = pnModGetVar('iw_forums','urladjunts');
		$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
		$update = pnModFunc('iw_main', 'user', 'updateFile', array('sv' => $sv,
																	'folder' => $folder,
																	'file' => $_FILES['adjunt']));
		// the function returns the error string if the update fails and and empty string if success
		if($update['msg'] != ''){
			LogUtil::registerError ($update['msg'].' '.__('An error has occurred in the attachment of the file. The message has been sent without the attached file.', $dom));
			$nom_fitxer = '';
		}else{
			$nom_fitxer = $update['fileName'];
		}
  	}
	if($titolmsg != '' && $msg != ''){
		$lid = pnModAPIFunc('iw_forums', 'user', 'crear_msg', array('fid' => $fid,
																	'ftid0' => $lidTema,
																	'titolmsg' => $titolmsg,
																	'msg' => $msg,
																	'adjunt' => $nom_fitxer,
																	'icon' => $icon));
		if ($lid == false) {
			// error creating message
			LogUtil::registerError (__('An error has occurred while creating a new message', $dom));
		}
	}
	return pnRedirect(pnModURL('iw_forums', 'user', 'forum', array('fid' => $fid)));
}

/**
 * Get the list of messages for a topic
 * @author	Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	the topic identity
 * @return	An array with the messages information
 */
function iw_forums_user_llista_msg($args)
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'REQUEST');
	$ftid = FormUtil::getPassedValue('ftid', isset($args['ftid']) ? $args['ftid'] : null, 'REQUEST');
	$u = FormUtil::getPassedValue('u', isset($args['u']) ? $args['u'] : 0, 'REQUEST');
	$inici = FormUtil::getPassedValue('inici', isset($args['inici']) ? $args['inici'] : null, 'REQUEST');
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	// check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access',
	                     array('fid' => $fid));
	if($access < 1){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	if(!is_numeric($u)){$u = 0;}
	if(!isset($inici) || $inici == ''){$inici = 1;}
	// get the forum information
	$registre = pnModAPIFunc('iw_forums', 'user', 'get',
	                          array('fid' => $fid));
 	if ($registre == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	if ($ftid > 0) {
		// get the topic information
		$topic = pnModAPIFunc('iw_forums', 'user', 'get_tema',
		                       array('fid' => $fid,
									 'ftid' => $ftid));
	}
	// check if user can moderate the forum
	$moderator = ($access == 4) ? true : false;
	// get all the messages to show
	$listmessages = pnModAPIFunc('iw_forums', 'user', 'getall_msg',
	                              array('ftid' => $ftid,
										'fid' => $registre['fid'],
										'usuari' => $u,
										'indent' => 0,
										'idparent' => 0,
										'inici' => $inici,
										'rpp' => 10));
	// process the messages
	foreach ($listmessages as $message) {
		if(isset($message)) $hi_ha_missatges = true;
		$imatge = (strpos($message['llegit'],'$'.pnUserGetVar( 'uid' ).'$' ) == 0) ? 'msgNo.gif' : 'msg.gif';
		if(strpos($message['marcat'],'$'.pnUserGetVar('uid').'$') == 0){
			$marcat = 'res.gif';
			$m = 1;
			$textmarca = __('Check the message', $dom);
		}else{
			$marcat = 'marcat.gif';
			$m = 0;
			$textmarca = __('Uncheck the message', $dom);
		}
		$temps_esborrat = $registre['msgDelTime'];
		$temps_edicio = $registre['msgEditTime'];
		$esborrable = false;
		$editable = false;
		if(time() < $message['data'] + 60 * $temps_esborrat && $message['usuari'] == pnUserGetVar('uid')){$esborrable = true;}
		if(time() < $message['data'] + 60 * $temps_edicio && $message['usuari'] == pnUserGetVar('uid')){$editable = true;}
		$messages[] = array('fmid' => $message['fmid'],
							'imatge' => $imatge,
							'title' => $message['titol'],
							'user' => $message['usuari'],
							'date' => date('d/m/y',$message['data']),
							'time' => date('H.i',$message['data']),
							'adjunt' => $message['adjunt'],
							'icon' => $message['icon'],
							'marcat' => $marcat,
							'm' => $m,
							'esborrable' => $esborrable,
							'editable' => $editable,
							'textmarca' => $textmarca,
							'indent' => $message['indent'],
							'oid' => $message['oid']);
	}
	// get users who have created a message
	$usuaris_rem = pnModAPIFunc('iw_forums', 'user', 'getremitents', array('ftid' => $ftid,
																			'fid' => $registre['fid']));
	foreach($usuaris_rem as $user){
		$usersList .= $user['usuari'].'$$';
	}	
	// get all users information
	$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
	$users = pnModFunc('iw_main', 'user', 'getAllUsersInfo', array('sv' => $sv,
																	'info' => 'ncc',
																	'list' => $usersList));
	$usuaris[] = array('id' => 0,
						'name' => __('Choose the sender...', $dom));
	foreach($usuaris_rem as $usuari_rem){
		if($users[$usuari_rem['usuari']] != ''){
			$usuaris[] = array('id' => $usuari_rem['usuari'],
								'name' => $users[$usuari_rem['usuari']]);
		}
	}
	$adjunts = ($registre['adjunts'] == 1) ? true : false;
	(pnModAvailable('bbsmile') && pnModIsHooked('bbsmile', 'iw_forums')) ? $pnRender -> assign('icons', true) : $pnRender -> assign('icons', false);
	$total = pnModAPIFunc('iw_forums', 'user', 'compta_msg', array('ftid' => $ftid,
																	'fid' => $fid,
																	'u' => $u));
	$pager = pnModFunc('iw_forums', 'user', 'pager', array('inici' => $inici,
															'total' => $total['nparent'],
															'rpp' => 10,
															'urltemplate' => 'index.php?module=iw_forums&func=llista_msg&inici=%%&fid=' . $fid . '&ftid=' . $ftid . '&u=' . $u));
	$pnRender -> assign('name', $registre['nom_forum']);
	$pnRender -> assign('topicName', $topic['titol']);
	$pnRender -> assign('adjunts', $adjunts);
	$pnRender -> assign('users', $users);
	$pnRender -> assign('access', $access);
	$pnRender -> assign('moderator', $moderator);
	$pnRender -> assign('messages', $messages);
	$pnRender -> assign('usuaris', $usuaris);
	$pnRender -> assign('u', $u);
	$pnRender -> assign('uname', $usersInfo[$u]);
	$pnRender -> assign('fid', $fid);
	$pnRender -> assign('ftid', $ftid);
	$pnRender -> assign('hi_ha_missatges', $hi_ha_missatges);
	$pnRender -> assign('pager', $pager);
	$pnRender -> assign('inici', $inici);
	return $pnRender -> fetch('iw_forums_user_forum.htm');
}

/**
 * Show the form for a new message
 * @author	Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	the message information in case of error
 * @return	An array with the messages information
 */
function iw_forums_user_nou_msg($args)
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'REQUEST');
	$ftid = FormUtil::getPassedValue('ftid', isset($args['ftid']) ? $args['ftid'] : null, 'REQUEST');
	$u = FormUtil::getPassedValue('u', isset($args['u']) ? $args['u'] : null, 'REQUEST');
	$titol = FormUtil::getPassedValue('titol', isset($args['titol']) ? $args['titol'] : null, 'POST');
	$msg = FormUtil::getPassedValue('msg', isset($args['msg']) ? $args['msg'] : null, 'POST');
	$fmid = FormUtil::getPassedValue('fmid', isset($args['fmid']) ? $args['fmid'] : null, 'REQUEST');
	$oid = FormUtil::getPassedValue('oid', isset($args['oid']) ? $args['oid'] : null, 'REQUEST');
	$inici = FormUtil::getPassedValue('inici', isset($args['inici']) ? $args['inici'] : null, 'REQUEST');
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	// check if user can access the forum
	if(pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid)) < 2){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	// get forum information
	$registre = pnModAPIFunc('iw_forums', 'user', 'get', array('fid' => $fid));
	if ($registre == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// if message have any answare get message information
	if($fmid != null){
		$missatge = pnModAPIFunc('iw_forums', 'user', 'get_msg', array('fmid' => $fmid));
		// get all users information
		$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
		$userInfo = pnModFunc('iw_main', 'user', 'getUserInfo', array('sv' => $sv,
																		'uid' => $missatge['usuari'],
																		'info' => 'ncc'));
		if($missatge == false){
			LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
			return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
		}
		$titol = (strpos($missatge['titol'], 'RE: ') === false) ? 'RE: ' . $missatge['titol'] : $missatge['titol'];
		$msg = '[quote='. $userInfo . ' ' . __("wrote on",$dom) . ' ' . date('d/m/Y H.i', $missatge['data']) . ']<br />' . $missatge['missatge'] . '<br />[/quote]';
	}else{
		$fmid = 0;
	}
	if(pnModAvailable('bbsmile') && pnModIsHooked('bbsmile', 'iw_forums')){
		$icons = pnModAPIFunc('bbsmile', 'user', 'getall');
		$pnRender -> assign('icons', $icons);
	}else{
		$pnRender -> assign('icons', false);
	}
	$pnRender -> assign('fid', $fid);
	$pnRender -> assign('ftid', $ftid);
	$pnRender -> assign('fmid', $fmid);
	$pnRender -> assign('name', $registre['nom_forum']);
	$pnRender -> assign('msg', $msg);	
	$pnRender -> assign('title', $titol);
	$pnRender -> assign('menu', $menu);
	$pnRender -> assign('adjunts', $registre['adjunts']);
	$pnRender -> assign('extensions', pnModGetVar('iw_main','extensions'));
	$pnRender -> assign('u', $u);
	$pnRender -> assign('inici', $inici);
	$pnRender -> assign('oid', $oid);
	return $pnRender -> fetch('iw_forums_user_new_msg.htm');
}

/*
FunciÃ³ que comprova que les dades enviades des del formulari de creaciÃ³ d'un
missatge s'ajusten al que ha de ser i envia l'ordre de crear el registre
*/
function iw_forums_user_crear_msg($args)
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'POST');
	$ftid = FormUtil::getPassedValue('ftid', isset($args['ftid']) ? $args['ftid'] : null, 'POST');
	$u = FormUtil::getPassedValue('u', isset($args['u']) ? $args['u'] : null, 'POST');
	$titol = FormUtil::getPassedValue('titol', isset($args['titol']) ? $args['titol'] : null, 'POST');
	$msg = FormUtil::getPassedValue('msg', isset($args['msg']) ? $args['msg'] : null, 'POST');
	$fmid = FormUtil::getPassedValue('fmid', isset($args['fmid']) ? $args['fmid'] : null, 'POST');
	$oid = FormUtil::getPassedValue('oid', isset($args['oid']) ? $args['oid'] : null, 'POST');
	$adjunt = FormUtil::getPassedValue('adjunt', isset($args['adjunt']) ? $args['adjunt'] : null, 'POST');
	$icon = FormUtil::getPassedValue('icon', isset($args['icon']) ? $args['icon'] : null, 'POST');
	$oldmsg = FormUtil::getPassedValue('oldmsg', isset($args['oldmsg']) ? $args['oldmsg'] : null, 'POST');
	// gets the attached file array
	$fileName = $_FILES['adjunt']['name'];
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	// confirm authorisation code
	if (!SecurityUtil::confirmAuthKey('iw_forums')) {
		return LogUtil::registerAuthidError (pnModURL('iw_forums', 'user', 'llista_msg', array('fid' => $fid,
																								'ftid' => $ftid)));
	}
	// check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid));
	if($access < 2){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	// get forum information
	$registre = pnModAPIFunc('iw_forums', 'user', 'get', array('fid' => $fid));
	if ($registre == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// check the needed values
	$nom_fitxer =  (empty($fileName)) ? '' : $fileName;
	// update the attached file to the server
	if($fileName != ''){
		$folder = pnModGetVar('iw_forums','urladjunts');
		$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
		$update = pnModFunc('iw_main', 'user', 'updateFile', array('sv' => $sv,
																	'folder' => $folder,
																	'file' => $_FILES['adjunt']));
		// the function returns the error string if the update fails and and empty string if success
		if($update['msg'] != ''){
			LogUtil::registerError ($update['msg'].' '.__('An error has occurred in the attachment of the file. The message has been sent without the attached file.', $dom));
			$nom_fitxer = '';
		}else{
			$nom_fitxer = $update['fileName'];
		}
  	}
	if($oldmsg != ''){
		$msg .= '<br />' . $oldmsg;
	}
	// create message
	$lid = pnModAPIFunc('iw_forums', 'user', 'crear_msg', array('fid' => $fid,
																'ftid' => $ftid,
																'titol' => $titol,
																'msg' => $msg,
																'adjunt' => $nom_fitxer,
																'icon' => $icon,
																'idparent' => $fmid,
																'oid' => $oid));
	// check if user canmoderate the forum
	$moderator = false;
	if($access == 4){$moderator = true;}
	if ($lid != false) {
		// message created successfuly
		$missatge = __('A new message has been created.', $dom);
		if(pnModGetVar('iw_forums','temps_edicio') > 0 && !$moderator){
			$missatge .= '<br />'.__('During the next ', $dom).pnModGetVar('iw_forums','temps_edicio').__(' munutes you can edit the message', $dom);
		}
		if(pnModGetVar('iw_forums','temps_esborrat')>0 && !$moderator){
			$missatge .= '<br />'.__('During the next ', $dom).pnModGetVar('iw_forums','temps_esborrat').__(' minutes you can delete the message', $dom);
		}
		LogUtil::registerStatus ($missatge);
	}else{
		LogUtil::registerError (__('An error has occurred while creating a new message', $dom));
	}
	if($ftid != 0){
		return pnRedirect(pnModURL('iw_forums', 'user', 'llista_msg', array('fid' => $fid,
																			'ftid' => $ftid,
																			'u' => $u)));
	}else{
		return pnRedirect(pnModURL('iw_forums', 'user', 'forum', array('fid' => $fid,
																		'u' => $u)));
	}
}

/*
	Shows message information
	@param $fmid:	Message id
	@param $ftid:	Topic id
	@param $fid:	Forum id
	@param $oid:	First thread message id
	@return:		Formated message
*/
function iw_forums_user_msg($args)
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'REQUEST');
	$ftid = FormUtil::getPassedValue('ftid', isset($args['ftid']) ? $args['ftid'] : null, 'REQUEST');
	$u = FormUtil::getPassedValue('u', isset($args['u']) ? $args['u'] : null, 'REQUEST');
	$fmid = FormUtil::getPassedValue('fmid', isset($args['fmid']) ? $args['fmid'] : null, 'REQUEST');
	$oid = FormUtil::getPassedValue('oid', isset($args['oid']) ? $args['oid'] : null, 'REQUEST');
	$inici = FormUtil::getPassedValue('inici', isset($args['inici']) ? $args['inici'] : null, 'REQUEST');
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	// check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid));
	if($access < 1){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get forum information
	$forum = pnModAPIFunc('iw_forums', 'user', 'get', array('fid' => $fid));
	if ($forum == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get message information
	$registre = pnModAPIFunc('iw_forums', 'user', 'get_msg', array('fmid' => $fmid,
																	'fid' => $fid));
	if ($registre == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));	
	}
	$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
	$userFullName = pnModFunc('iw_main', 'user', 'getUserInfo', array('sv' => $sv,
																		'info' => 'ncc',
																		'uid' => $registre['usuari']));
	// set user as message reader
	if (strpos($registre['llegit'],'$'.pnUserGetVar('uid').'$') == 0){
		$llegit = pnModApiFunc('iw_forums', 'user', 'llegit', array('fmid' => $registre['fmid'],
																	'llegit' => $registre['llegit']));
		$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
		pnModFunc('iw_main', 'user', 'userSetVar', array('module' => 'iw_main_block_news',
															'name' => 'have_news',
															'value' => 'fo',
															'sv' => $sv));
	}
	// prepare printing messages
	$printer .= "<table width=100%>";
	$printer .= '<tr><td><font face=Arial color=navy><strong>'.$registre['titol'].'</font></td></tr>';
	$printer .= '<tr><td>'.__('From: ', $dom).'<font face=Arial color=green><strong>'.$usersName.'</strong></td></tr>';
	$printer .= '<tr><td>'.__('Date', $dom).': <font face=Arial size=2 color=696969><strong>'.date('d/m/y',$registre['data']).'</strong></font></td></tr>';
	$printer .= '<tr><td>'.__('Time', $dom).': <font face=Arial size=2 color=696969><strong>'.date('H.i',$registre['data']).'</strong></font></td></tr>';
	if($registre['adjunt'] != ""){
		$printer .= '<tr><td>'.__('Attached file', $dom).': '.$registre['adjunt'].'</td></tr>';
	}	
	$printer .= '<tr><td><hr></td></tr>';
	$printer .= '<tr><td>'.pnModFunc('iw_forums','user','prepara_print',array('text'=>$registre['missatge'])).'</td></tr>';
	$printer .= '<tr><td><hr></td></tr>';
	$printer .= "</table><br>";
	$marcat = (strpos($registre['marcat'],'$'.pnUserGetVar('uid').'$') == 0) ? false : true;
	$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
	$photo = pnModFunc('iw_main', 'user', 'getUserPicture', array('uname' => pnUserGetVar('uname',$registre['usuari']),
																	'sv' => $sv));
	$pnRender -> assign('marcat', $marcat); // $marcat is reused later
	// ff user didn't click a first-level message, get the first-level message
	if ($oid != $fmid) {
		// get message information
		$origen = pnModAPIFunc('iw_forums', 'user', 'get_msg', array('fmid' => $oid,
																		'fid' => $fid));
		if ($origen == false) {
			LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
			return pnRedirect(pnModURL('iw_forums', 'user', 'main'));	
		}
	}
	else $origen = $registre;
	// process the first message
	$imatge = (strpos($origen['llegit'],'$'.pnUserGetVar('uid').'$') == 0) ? 'msgNo.gif' : 'msg.gif';
	$marcat = (strpos($origen['marcat'],'$'.pnUserGetVar('uid').'$') == 0) ? 'res.gif' : 'marcat.gif';
	$m = (strpos($origen['marcat'],'$'.pnUserGetVar('uid').'$') == 0) ? 1 : 0;
	$textmarca = (strpos($origen['marcat'],'$'.pnUserGetVar('uid').'$') == 0) ? __("Check the message",$dom) : __('Uncheck the message', $dom);
	$temps_esborrat = $forum['msgDelTime'];
	$temps_edicio = $forum['msgEditTime'];
	$esborrable = (time() < $origen['data'] + 60 * $temps_esborrat && $origen['usuari'] == pnUserGetVar('uid')) ? true : false;
	$editable =  (time() < $origen['data'] + 60 * $temps_edicio && $origen['usuari'] == pnUserGetVar('uid')) ? true : false;
	$messages[] = array('fmid' => $origen['fmid'],
						'imatge' => $imatge,
						'title' => $origen['titol'],
						'u' => $origen['usuari'],
						'user' => $userFullName,
						'date' => date('d/m/y',$origen['data']),
						'time' => date('H.i',$origen['data']),
						'adjunt' => $origen['adjunt'],
						'icon' => $origen['icon'],
						'marcat' => $marcat,
						'm' => $m,
						'esborrable' => $esborrable,
						'editable' => $editable,
						'textmarca' => $textmarca,
						'indent' => 0,
						'oid' => $oid);
	// get the messages of the thread where the message belongs
	$listmessages = pnModAPIFunc('iw_forums', 'user', 'getall_msg', array('ftid' => $ftid,
																			'fid' => $fid,
																			'usuari' => 0,
																			'indent' => 0,
																			'idparent' => $oid,
																			'tots' => 1,
																			'inici' => 0,
																			'rpp' => 10));
	$usersList = $origen['usuari'].'$$';
	// process the messages
	foreach($listmessages as $message){
		if(isset($message)) $hi_ha_missatges = true;
		$imatge = (strpos($message['llegit'],'$'.pnUserGetVar( 'uid' ).'$') == 0) ? 'msgNo.gif' : 'msg.gif';
		$usersList .= $message['usuari'].'$$';
		$marcat = (strpos($message['marcat'],'$'.pnUserGetVar('uid').'$') == 0) ? 'res.gif' : 'marcat.gif';
		$m = (strpos($message['marcat'],'$'.pnUserGetVar('uid').'$') == 0) ? 1 : 0;
		$textmarca = (strpos($message['marcat'],'$'.pnUserGetVar('uid').'$') == 0) ? __("Check the message",$dom) : __('Uncheck the message', $dom);
		$esborrable = (time() < $message['data'] + 60 * $temps_esborrat && $message['usuari'] == pnUserGetVar('uid')) ? true : false;
		$editable = (time() < $message['data'] + 60 * $temps_edicio && $message['usuari'] == pnUserGetVar('uid')) ? true : false;
		$messages[] = array('fmid' => $message['fmid'],
							'imatge' => $imatge,
							'title' => $message['titol'],
							'u' => $message['usuari'],
							'user' => $userFullName,
							'date' => date('d/m/y',$message['data']),
							'time' => date('H.i',$message['data']),
							'adjunt' => $message['adjunt'],
							'icon' => $message['icon'],
							'marcat' => $marcat,
							'm' => $m,
							'esborrable' => $esborrable,
							'editable' => $editable,
							'textmarca' => $textmarca,
							'indent' => $message['indent'] + 30,
							'oid' => $oid);
	}
	// get all users information
	$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
	$users = pnModFunc('iw_main', 'user', 'getAllUsersInfo', array('sv' => $sv,
																	'info' => 'ncc',
																	'list' => $usersList));
	// get smarticons if module bbsmile is active
	if(pnModAvailable('bbsmile') && pnModIsHooked('bbsmile', 'iw_forums')){
		$icons = pnModAPIFunc('bbsmile', 'user', 'getall');
		$pnRender -> assign('icons', $icons);
	} else {
		$pnRender -> assign('icons', false);
	}
	$adjunts = ($forum['adjunts'] == 1) ? true : false;
	// get file extension
	$fileExtension = strtolower(substr(strrchr($registre['adjunt'],"."),1));
	// get file icon
	$ctypeArray = pnModFunc('iw_main', 'user', 'getMimetype', array('extension' => $fileExtension));
	$fileIcon = $ctypeArray['icon'];
	$pnRender -> assign('users', $users);
	$pnRender -> assign('fileIcon', $fileIcon);
	$pnRender -> assign('icons', $icons);
	$pnRender -> assign('oid', $oid);
	$pnRender -> assign('fmid', $fmid);
	$pnRender -> assign('messages', $messages);
	$pnRender -> assign('origen', $origen);
	$pnRender -> assign('ftid', $ftid);
	$pnRender -> assign('fid', $fid);
	$pnRender -> assign('u', $u);
	$pnRender -> assign('inici', $inici);
	$pnRender -> assign('menu', $menu);
	$pnRender -> assign('avatarsVisible', pnModGetVar('iw_forums','avatarsVisible'));
	$pnRender -> assign('title', $registre['titol']);
	$pnRender -> assign('message', $registre['missatge']);
	$pnRender -> assign('adjunt', $registre['adjunt']);
	$pnRender -> assign('adjunts', $adjunts);
	$pnRender -> assign('user', $userFullName);
	$pnRender -> assign('date', date('d/m/y',$registre['data']));
	$pnRender -> assign('time', date('H:i',$registre['data']));
	$pnRender -> assign('photo', $photo);
	$pnRender -> assign('foto', pnModGetVar('iw_forums','fotos'));
	$pnRender -> assign('urladjunts', pnModGetVar('iw_forums','urladjunts'));
	return $pnRender -> fetch('iw_forums_user_msg.htm');
}

/*
	Shows message information
	@param $fmid:	Message id
	@param $ftid:	Topic id
	@param $fid:	Forum id
	@param $oid:	First thread message id
	@return:		Formated message
*/
function iw_forums_user_openMsg($args)
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'REQUEST');
	$ftid = FormUtil::getPassedValue('ftid', isset($args['ftid']) ? $args['ftid'] : null, 'REQUEST');
	$u = FormUtil::getPassedValue('u', isset($args['u']) ? $args['u'] : null, 'REQUEST');
	$fmid = FormUtil::getPassedValue('fmid', isset($args['fmid']) ? $args['fmid'] : null, 'REQUEST');
	$oid = FormUtil::getPassedValue('oid', isset($args['oid']) ? $args['oid'] : null, 'REQUEST');
	$inici = FormUtil::getPassedValue('inici', isset($args['inici']) ? $args['inici'] : null, 'REQUEST');
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	// check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid));
	if($access < 1){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get forum information
	$forum = pnModAPIFunc('iw_forums', 'user', 'get', array('fid' => $fid));
	if ($forum == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get message information
	$registre = pnModAPIFunc('iw_forums', 'user', 'get_msg', array('fmid' => $fmid,
																	'fid' => $fid));
	if ($registre == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));	
	}
	// set user as message reader
	if (strpos($registre['llegit'],'$'.pnUserGetVar('uid').'$') == 0){
		$llegit = pnModApiFunc('iw_forums', 'user', 'llegit', array('fmid' => $registre['fmid'],
																	'llegit' => $registre['llegit']));
		$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
		pnModFunc('iw_main', 'user', 'userSetVar', array('module' => 'iw_main_block_news',
															'name' => 'have_news',
															'value' => 'fo',
															'sv' => $sv));
	}
	// get file extension
	$fileExtension = strtolower(substr(strrchr($registre['adjunt'],"."),1));
	// get file icon
	$ctypeArray = pnModFunc('iw_main', 'user', 'getMimetype', array('extension' => $fileExtension));
	$fileIcon = $ctypeArray['icon'];
	
	$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
	$photo = pnModFunc('iw_main', 'user', 'getUserPicture', array('uname' => pnUserGetVar('uname',$registre['usuari']) . '_s',
																	'sv' => $sv));
	$pnRender -> assign('photo', $photo);
	$pnRender -> assign('message', $registre['missatge']);
	$pnRender -> assign('adjunt', $registre['adjunt']);
	$pnRender -> assign('fileIcon', $fileIcon);
	$pnRender -> assign('adjunts', $adjunts);
	$pnRender -> assign('u', $u);
	$pnRender -> assign('inici', $inici);
	$pnRender -> assign('fmid', $fmid);
	$pnRender -> assign('ftid', $ftid);
	$pnRender -> assign('fid', $fid);
	$pnRender -> assign('oid', $oid);
	$pnRender -> assign('access', $access);
	return $pnRender -> fetch('iw_forums_user_openMsg.htm');
}

/**
 * Get a file from a server folder even it is out of the public html directory
 * @author:     Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	name of the file that have to be gotten
 * @return:	The file information
*/
function iw_forums_user_getFile($args)
{
	// file name with the path
	$fileName = FormUtil::getPassedValue('fileName', isset($args['fileName']) ? $args['fileName'] : 0, 'GET');
	// security check
	if (!SecurityUtil::checkPermission('iw_forums::', "::", ACCESS_READ)) {
		return LogUtil::registerError(_MODULENO, 403);
	}
	$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
	return pnModFunc('iw_main', 'user', 'getFile', array('fileName' => $fileName,
									'sv' => $sv));
}

/**
 * Download a file
 * @author:     Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	name of the file that have to be downloaded
 * @return:	The file required
*/
function iw_forums_user_download($args)
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	// get the parameters
	$fmid = FormUtil::getPassedValue('fmid', isset($args['fmid']) ? $args['fmid'] : null, 'GET');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'GET');
	$fileName = FormUtil::getPassedValue('fileName', isset($args['fileName']) ? $args['fileName'] : 0, 'GET');
	// security check
	if (!SecurityUtil::checkPermission('iw_forums::', "::", ACCESS_READ)) {
		return LogUtil::registerError(_MODULENO, 403);
	}
	// needed argument
	if (!isset($fileName) || !isset($fmid) || !isset($fid)) {
		return LogUtil::registerError (__('Error! Could not do what you wanted. Please check your input.', $dom));
	}
	// check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid));
	if($access < 1){
		LogUtil::registerError (__('You are not allowed to do this action', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	$fileNameInServer = pnModGetVar('iw_forums','urladjunts').'/'.$fileName;
	$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
	return pnModFunc('iw_main', 'user', 'downloadFile', array('fileName' => $fileName,
																'fileNameInServer' => $fileNameInServer,
																'sv' => $sv));

}

/**
 * Flagged or unflagged a message
 * @or:     Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	main information for the message
 * @return:	Redirect user to main page
*/
function iw_forums_user_marca($args)
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fmid = FormUtil::getPassedValue('fmid', isset($args['fmid']) ? $args['fmid'] : null, 'GET');
	$ftid = FormUtil::getPassedValue('ftid', isset($args['ftid']) ? $args['ftid'] : null, 'GET');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'GET');
	$u = FormUtil::getPassedValue('u', isset($args['u']) ? $args['u'] : null, 'GET');
	$m = FormUtil::getPassedValue('m', isset($args['m']) ? $args['m'] : null, 'GET');
	$msg = FormUtil::getPassedValue('msg', isset($args['msg']) ? $args['msg'] : null, 'GET');
	$inici = FormUtil::getPassedValue('inici', isset($args['inici']) ? $args['inici'] : null, 'GET');
	$oid = FormUtil::getPassedValue('oid', isset($args['oid']) ? $args['oid'] : null, 'GET');
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	// get forum information
	$forum = pnModAPIFunc('iw_forums', 'user', 'get', array('fid' => $fid));
	if ($forum == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid));
	if($access < 1){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get message information
	$registre = pnModAPIFunc('iw_forums', 'user', 'get_msg', array('fmid' => $fmid));
	if($registre == false){
		LogUtil::registerError(__('No messages have been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	$marcat = ($m == 1) ? $registre['marcat'].'$'.pnUserGetVar('uid').'$' : str_replace('$'.pnUserGetVar('uid').'$','',$registre['marcat']);
	$ha_marcat = pnModAPIFunc('iw_forums', 'user', 'marcat', array('marcat' => $marcat,
																	'fmid' => $fmid));
	$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
	pnModFunc('iw_main', 'user', 'userSetVar', array('module' => 'iw_main_block_flagged',
														'name' => 'have_flags',
														'value' => 'fo',
														'sv' => $sv));
	if($ftid != 0){
		if(isset($msg)){
		   	return pnRedirect(pnModURL('iw_forums', 'user', 'msg', array('fid' => $fid,
																			'u' => $u,
																			'ftid' => $ftid,
																			'fmid' => $fmid,
																			'inici' => $inici,
																			'oid' => $oid)));
		}else{
			return pnRedirect(pnModURL('iw_forums', 'user', 'llista_msg', array('fid' => $fid,
																				'u' => $u,
																				'ftid' => $ftid,
																				'inici' => $inici,
																				'oid' => $oid)));
		}
	}else{
		if(isset($msg)){
			return pnRedirect(pnModURL('iw_forums', 'user', 'msg', array('fid' => $fid,
																			'u' => $u,
																			'ftid' => $ftid,
																			'fmid' => $fmid,
																			'inici' => $inici,
																			'oid' => $oid)));
		}else{
			return pnRedirect(pnModURL('iw_forums', 'user', 'forum', array('fid' => $fid,
																			'u' => $u,
																			'inici' => $inici,
																			'oid' => $oid)));
		}
	}
}

/**
 * Get the list of users that has readed a message
 * @author:     Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	message, topic and forum identities
 * @return:	Redirect user to readers page
*/
function iw_forums_user_lectors($args)
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fmid = FormUtil::getPassedValue('fmid', isset($args['fmid']) ? $args['fmid'] : null, 'GET');
	$ftid = FormUtil::getPassedValue('ftid', isset($args['ftid']) ? $args['ftid'] : null, 'GET');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'GET');
	$oid = FormUtil::getPassedValue('oid', isset($args['oid']) ? $args['oid'] : null, 'GET');
	$u = FormUtil::getPassedValue('u', isset($args['u']) ? $args['u'] : null, 'GET');
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	// check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid));
	if($access < 1){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get message information
	$registre = pnModAPIFunc('iw_forums', 'user', 'get_msg', array('fmid' => $fmid));
	if ($registre == false) {
		LogUtil::registerError (__('No messages have been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get forum information
	$tema = pnModAPIFunc('iw_forums', 'user', 'get', array('fid' => $fid));
	if ($tema == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	$lectors = explode('$$', substr($registre['llegit'],2,-1));
	$usersList = '$$';
	foreach($lectors as $lector){
		$usersList .= $lector . '$$';
	}
	// get all users information
	$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
	$usersInfo = pnModFunc('iw_main', 'user', 'getAllUsersInfo', array('sv' => $sv,
																		'info' => 'ccn',
																		'list' => $usersList));
	$readers = array();
	foreach($lectors as $lector){
		$readers[] = array('user' => $usersInfo[$lector]);
	}
	sort($readers);
	$pnRender -> assign('readers',$readers);
	$pnRender -> assign('menu',$menu);
	$pnRender -> assign('fid', $fid);
	$pnRender -> assign('ftid', $ftid);
	$pnRender -> assign('fmid', $fmid);
	$pnRender -> assign('oid', $oid);
	$pnRender -> assign('u', $u);
	return $pnRender -> fetch('iw_forums_user_readers.htm');
}

/**
 * Delete a message
 * @author:     Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	message, topic and forum identities
 * @return:	Redirect user to readers page
*/
function iw_forums_user_del($args){
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fmid = FormUtil::getPassedValue('fmid', isset($args['fmid']) ? $args['fmid'] : null, 'REQUEST');
	$ftid = FormUtil::getPassedValue('ftid', isset($args['ftid']) ? $args['ftid'] : null, 'REQUEST');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'REQUEST');
	$confirmation = FormUtil::getPassedValue('confirmation', isset($args['confirmation']) ? $args['confirmation'] : null, 'POST');
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	// check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid));
	if($access < 2){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get forum information
	$forum = pnModAPIFunc('iw_forums', 'user', 'get', array('fid' => $fid));
	if ($forum == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get message information
	$missatge = pnModAPIFunc('iw_forums', 'user', 'get_msg', array('fmid' => $fmid));
	if ($missatge == false) {
		LogUtil::registerError (__('No messages have been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get user information
	$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
	$userInfo = pnModFunc('iw_main', 'user', 'getUserInfo', array('sv' => $sv,
																	'uid' => $missatge['usuari'],
																	'info' => 'ncc'));
	if($ftid != 0){
		// get topic information
		$tema = pnModAPIFunc('iw_forums', 'user', 'get_tema', array('ftid' => $ftid,
																	'fid' => $fid));
		if ($tema == false) {
			LogUtil::registerError (__('No messages have been found', $dom));
			return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
		}
	}
	$moderator = ($access == 4) ? true: false;
	// check if user can delete the message
	if(!$moderator && (time() > $missatge['data'] + 60 * $forum['msgDelTime'] || $missatge['usuari'] != pnUserGetVar('uid'))){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// check if the message is parent
	if(pnModAPIFunc('iw_forums', 'user', 'is_parent', array('fmid' => $fmid))){
		LogUtil::registerError (__('The message can not be deleted because have answers. You can move the answers to an other theme or forum.', $dom));
		if($ftid!=0){
			return pnRedirect(pnModURL('iw_forums', 'user', 'llista_msg', array('fid' => $fid,
												'ftid' => $ftid)));
		}else{
			return pnRedirect(pnModURL('iw_forums', 'user', 'forum', array('fid' => $fid)));
		}		
	}
	// axk of deleteion confirmation
	if (empty($confirmation)) {
		$pnRender -> assign('name', $forum['nom_forum']);
		$pnRender -> assign('tema', $tema['titol']);
		$pnRender -> assign('ftid', $ftid);
		$pnRender -> assign('fid', $fid);
		$pnRender -> assign('fmid', $fmid);
		$pnRender -> assign('msg_title', $missatge['titol']);
		$pnRender -> assign('user', $userInfo);
		$pnRender -> assign('date', date('d/m/y',$missatge['data']));
		$pnRender -> assign('time', date('H.i',$missatge['data']));
		$pnRender -> assign('message', $missatge['missatge']);
		return $pnRender->fetch('iw_forums_user_del_msg.htm');
	}
	// Confirm authorisation code
	if (!SecurityUtil::confirmAuthKey('iw_forums')) {
		return LogUtil::registerAuthidError (pnModURL('iw_forums', 'user', 'llista_msg', array('fid' => $fid,
																								'ftid' => $ftid)));
	}
	// delete message
	if (pnModAPIFunc('iw_forums', 'user', 'del_msg', array('fmid' => $fmid))) {
		// deletion successfuly
		LogUtil::registerStatus (__('The message has been deleted.', $dom));
		// delete attached files is exist
		if($missatge['adjunt'] != ''){
			unlink(pnModGetVar('iw_main','documentRoot') . '/' . pnModGetVar('iw_forums','urladjunts') . '/' . $missatge['adjunt']);
		}		
	}
	// redirect user to the list of messages
	if($ftid != 0){
		return pnRedirect(pnModURL('iw_forums', 'user', 'llista_msg', array('fid' => $fid,
																			'ftid' =>$ftid)));
	}else{
		return pnRedirect(pnModURL('iw_forums', 'user', 'forum', array('fid' => $fid)));
	}
}

/**
 * Edit a message
 * @author:   Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	message, topic and forum identities
 * @return:	Show a form for message edition
*/
function iw_forums_user_edit_msg($args) {
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fmid = FormUtil::getPassedValue('fmid', isset($args['fmid']) ? $args['fmid'] : null, 'REQUEST');
	$ftid = FormUtil::getPassedValue('ftid', isset($args['ftid']) ? $args['ftid'] : null, 'REQUEST');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'REQUEST');
	$titol = FormUtil::getPassedValue('titol', isset($args['titol']) ? $args['titol'] : null, 'POST');
	$msg = FormUtil::getPassedValue('msg', isset($args['msg']) ? $args['msg'] : null, 'POST');
	$u = FormUtil::getPassedValue('u', isset($args['u']) ? $args['u'] : null, 'REQUEST');
	$inici = FormUtil::getPassedValue('inici', isset($args['inici']) ? $args['inici'] : null, 'REQUEST');
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	//check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid));
	if($access < 2){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get forum information
	$registre = pnModAPIFunc('iw_forums','user','get',array('fid' => $fid));
	if ($registre == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get message information
	$missatge = pnModAPIFunc('iw_forums', 'user', 'get_msg', array('fmid' => $fmid));
	if ($missatge == false) {
		LogUtil::registerError (__('No messages have been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	$moderator = ($access == 4) ? true : false;
	if(!$moderator && (time() > $missatge['data'] + 60 * $registre['msgEditTime'] || $missatge['usuari'] != pnUserGetVar('uid'))){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));			
	}
	// get smarticons if bbsmile is active
	if(pnModAvailable('bbsmile') && pnModIsHooked('bbsmile', 'iw_forums')){
		$icons = pnModAPIFunc('bbsmile', 'user', 'getall');
		$pnRender -> assign('icons', $icons);
	} else {
		$pnRender -> assign('icons', false);
	}
	// Separate the message from the quotes
	$quotes = stristr($missatge['missatge'], '[quote=');
	$message = ($quotes != '') ? substr($missatge['missatge'], 0, - (strlen($quotes) + 6)) : $missatge['missatge'];
	$missatge['quotes'] = $quotes;
	$missatge['missatge'] = $message;
	$pnRender -> assign('fid', $fid);
	$pnRender -> assign('ftid', $ftid);
	$pnRender -> assign('missatge',$missatge);
	$pnRender -> assign('menu', $menu);
	$pnRender -> assign('name', $registre['nom_forum']);
	$pnRender -> assign('adjunts', $registre['adjunts']);
	$pnRender -> assign('extensions', pnModGetVar('iw_main','extensions'));
	$pnRender -> assign('u', $u);
	return $pnRender -> fetch('iw_forums_user_edit_msg.htm');
}

/**
 * Update a message with the information received from database
 * @author:   Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	message information
 * @return:	Return user to messages list
*/
function iw_forums_user_update_msg($args)
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fmid = FormUtil::getPassedValue('fmid', isset($args['fmid']) ? $args['fmid'] : null, 'POST');
	$ftid = FormUtil::getPassedValue('ftid', isset($args['ftid']) ? $args['ftid'] : null, 'POST');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'POST');
	$titol = FormUtil::getPassedValue('titol', isset($args['titol']) ? $args['titol'] : null, 'POST');
	$msg = FormUtil::getPassedValue('msg', isset($args['msg']) ? $args['msg'] : null, 'POST');
	$u = FormUtil::getPassedValue('u', isset($args['u']) ? $args['u'] : null, 'POST');
	$inici = FormUtil::getPassedValue('inici', isset($args['inici']) ? $args['inici'] : null, 'POST');
	$oldmsg = FormUtil::getPassedValue('oldmsg', isset($args['oldmsg']) ? $args['oldmsg'] : null, 'POST');
	$adjunt = FormUtil::getPassedValue('adjunt', isset($args['adjunt']) ? $args['adjunt'] : null, 'POST');
	$icon = FormUtil::getPassedValue('icon', isset($args['icon']) ? $args['icon'] : null, 'POST');
	$fileName = $_FILES['adjunt']['name'];
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	// confirm authorisation code
	if (!SecurityUtil::confirmAuthKey('iw_forums')) {
		return LogUtil::registerAuthidError (pnModURL('iw_forums', 'user', 'llista_msg', array('fid' => $fid,
																								'ftid' => $ftid)));
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	//check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid));
	if($access < 2){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get forum information
	$registre = pnModAPIFunc('iw_forums','user','get',array('fid' => $fid));
	if ($registre == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get the file name
	$nom_adjunt =  (empty($fileName)) ? '' : $fileName;
	if ($oldmsg != null) $msg = $oldmsg;
	$moderator = ($access == 4) ? true : false;
	// get message information
	$missatge = pnModAPIFunc('iw_forums', 'user', 'get_msg', array('fmid' => $fmid));
	if ($missatge == false) {
		LogUtil::registerError (__('No messages have been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	if(!$moderator && (time() > $missatge['data'] + 60 * $registre['msgEditTime'] || $missatge['usuari'] != pnUserGetVar('uid'))){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// update the attached file to the server
	if($nom_adjunt != '' && $registre['adjunts']){
		$folder = pnModGetVar('iw_forums','urladjunts');
		$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
		$update = pnModFunc('iw_main', 'user', 'updateFile', array('sv' => $sv,
																	'folder' => $folder,
																	'file' => $_FILES['adjunt']));
		//the function returns the error string if the update fails and and empty string if success
		if($update['msg'] != ''){
			LogUtil::registerError ($update['msg'] . ' ' . __('Probably the message has been sended without the attached file.', $dom));
			$nom_fitxer = '';
		}else{
			$nom_fitxer = $update['fileName'];
		}
	}else{
		$nom_fitxer = $missatge['adjunt'];
	}
	$lid = pnModAPIFunc('iw_forums', 'user', 'update_msg', array('fmid' => $fmid,
																	'titol' => $titol,
																	'msg' => $msg,
																	'fadjunt' => $nom_fitxer,
																	'icon' => $icon));
	if ($lid != false) {
		// creation success
		LogUtil::registerStatus(__('The message has been modified', $dom));
	}else{
		LogUtil::registerError(__('Error trying to edit the message', $dom));
	}
	if($ftid != 0){
		return pnRedirect(pnModURL('iw_forums', 'user', 'llista_msg',array('fid'=>$fid,'ftid'=>$ftid,'u'=>$u)));
	}else{
		return pnRedirect(pnModURL('iw_forums', 'user', 'forum',array('fid'=>$fid,'u'=>$u)));
	}
}

/**
 * Move a message between topics or and forums
 * @author:   Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	message information
 * @return:	Return user to messages list
*/
function iw_forums_user_mou($args)
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fmid = FormUtil::getPassedValue('fmid', isset($args['fmid']) ? $args['fmid'] : null, 'REQUEST');
	$ftid = FormUtil::getPassedValue('ftid', isset($args['ftid']) ? $args['ftid'] : null, 'REQUEST');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'REQUEST');
	$moutema = FormUtil::getPassedValue('moutema', isset($args['moutema']) ? $args['moutema'] : null, 'REQUEST');
	$u = FormUtil::getPassedValue('u', isset($args['u']) ? $args['u'] : null, 'REQUEST');
	$nouforum = FormUtil::getPassedValue('nouforum', isset($args['nouforum']) ? $args['nouforum'] : null, 'POST');
	$noutema = FormUtil::getPassedValue('noutema', isset($args['noutema']) ? $args['noutema'] : null, 'REQUEST');
	$inici = FormUtil::getPassedValue('inici', isset($args['inici']) ? $args['inici'] : null, 'REQUEST');
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	// check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid));
	if($access < 4){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	$forumtriat = ($moutema == 1) ? $nouforum : $fid;
	// get forum information
	$forum = pnModAPIFunc('iw_forums','user','get',array('fid' => $fid));
	if ($forum == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get message information
	$missatge = pnModAPIFunc('iw_forums', 'user', 'get_msg', array('fmid' => $fmid));
	if ($missatge == false) {
		LogUtil::registerError (__('No messages have been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	if($ftid != 0){
		// get topic information
		$tema = pnModAPIFunc('iw_forums', 'user','get_tema', array('ftid' => $ftid,
																	'fid' => $fid));
		if ($tema == false) {
			LogUtil::registerError (__('No messages have been found', $dom));
			return pnRedirect(pnModURL('iw_forums', 'user', 'main'));		
		}
	}
	// get moderators list
	$forums = pnModAPIFunc('iw_forums', 'user', 'getall');
	foreach($forums as $forumlist){
		$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $forumlist['fid']));
		if($access == 4){
			$modera[] = array('fid' => $forumlist['fid'],
						'nom_forum' => $forumlist['nom_forum']);
		}		
	}
	// get list of topics
	$temes = pnModAPIFunc('iw_forums', 'user', 'get_temes', array('forumtriat' => $forumtriat));
	// ask for change position
	if ($moutema == "" || $moutema == 1) {
		$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
		$userFullName = pnModFunc('iw_main', 'user', 'getUserInfo', array('sv' => $sv,
																			'info' => 'ncc',
																			'uid' => $missatge['usuari']));
		$pnRender -> assign('modera',$modera);
		$pnRender -> assign('name', $forum['nom_forum']);
		$pnRender -> assign('tema', $tema['titol']);
		$pnRender -> assign('ftid',$ftid);
		$pnRender -> assign('fid', $fid);
		if(!isset($nouforum)){$nouforum = $fid;}
		$pnRender -> assign('nouforum', $nouforum);
		$pnRender -> assign('fmid', $fmid);		
		$pnRender -> assign('security', $security);
		$pnRender -> assign('msg_title', $missatge['titol']);
		$pnRender -> assign('user', $userFullName);
		$pnRender -> assign('date', date('d/m/y',$missatge['data']));
		$pnRender -> assign('time', date('H.i',$missatge['data']));
		$pnRender -> assign('message', $missatge['missatge']);
		$pnRender -> assign('temes', $temes);
		$pnRender -> assign('u', $u);
		return $pnRender->fetch('iw_forums_user_move_msg.htm');	
	}
	// confirm authorisation code
	if (!SecurityUtil::confirmAuthKey('iw_forums')) {
		return LogUtil::registerAuthidError (pnModURL('iw_forums', 'user', 'llista_msg', array('fid' => $fid,
																								'ftid' => $ftid,
																								'u' => $u)));
	}
	// check if user can access the forum as moderator
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $nouforum));
	if($access < 4){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	($noutema == -1) ? $noutema = 0 : "";
	// send the message to the new topic
	if (pnModAPIFunc('iw_forums', 'user', 'mou', array('fmid' => $fmid,
														'noutema' => $noutema,
														'nouforum' => $nouforum,
														'fid' => $fid,
														'ftid' => $ftid))) {
		// success change of position
		LogUtil::registerStatus (__('The message has been transferred', $dom));
	}
	// redirect user to messages list
	if($ftid!=0){
		return pnRedirect(pnModURL('iw_forums', 'user', 'llista_msg', array('fid' => $fid,
																			'ftid' => $ftid,
																			'u' => $u)));
	}else{
		return pnRedirect(pnModURL('iw_forums', 'user', 'forum', array('fid' => $fid,
																		'u' => $u)));
	}
}

/**
 * Set as red all the messages in a forum
 * @author:   Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	the forum identity
 * @return:	Return user to messages list
*/
function iw_forums_user_llegits($args)
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'REQUEST');
	$inici = FormUtil::getPassedValue('inici', isset($args['inici']) ? $args['inici'] : null, 'REQUEST');
	$ftid = FormUtil::getPassedValue('ftid', isset($args['ftid']) ? $args['ftid'] : null, 'REQUEST');
	$u = FormUtil::getPassedValue('u', isset($args['u']) ? $args['u'] : null, 'REQUEST');
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	// check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid));
	if($access < 1){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get forum information
	$registre = pnModAPIFunc('iw_forums', 'user', 'get', array('fid' => $fid));
	if ($registre == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get messages information
	$missatges = pnModAPIFunc('iw_forums', 'user', 'getall_msg_unread', array('fid' => $fid));
	// mark messages as readed
	foreach($missatges as $missatge){
		if(strpos($missatge['llegit'],'$'.pnUserGetVar('uid').'$') == 0){
			pnModApiFunc('iw_forums', 'user', 'llegit', array('fmid' => $missatge['fmid'],
																'llegit' => $missatge['llegit']));
			$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
			pnModFunc('iw_main', 'user', 'userSetVar', array('module' => 'iw_main_block_news',
																'name' => 'have_news',
																'value' => 'fo',
																'sv' => $sv));
		}	
	}
	if($ftid == null){
		return pnRedirect(pnModURL('iw_forums', 'user', 'forum', array('fid' => $fid,
																		'inici' => $inici,
																		'u' => $u)));
	}else{
		return pnRedirect(pnModURL('iw_forums', 'user', 'llista_msg', array('fid' => $fid,
																			'ftid' => $ftid,
																			'inici' => $inici,
																			'u' => $u)));
	}
}

/**
 * Get and show all the messages into a forum
 * @author:   Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	the forum identity
 * @return:	Return the content in all messages
*/
function iw_forums_user_allmsg($args)
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'REQUEST');
	$ftid = FormUtil::getPassedValue('ftid', isset($args['ftid']) ? $args['ftid'] : null, 'REQUEST');
	$u = FormUtil::getPassedValue('u', isset($args['u']) ? $args['u'] : null, 'REQUEST');
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	// check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid));
	if($access < 1){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get forum information
	$forum = pnModAPIFunc('iw_forums','user','get',array('fid' => $fid));
	if($forum == false){
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));		
	}
	// get messages information
	$missatges_llista = pnModAPIFunc('iw_forums', 'user', 'getall_msg', array('fid' => $fid,
																				'ftid' => $ftid,
																				'usuari' =>$u,
																				'indent' => 0,
																				'idparent' => 0,
																				'inici' => 1,
																				'rpp' => 100000000));
	if ($missatges_llista == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));	
	}
	$usersList = '$$';
	foreach($missatges_llista as $missatge){
		$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
		$photo = pnModFunc('iw_main', 'user', 'getUserPicture', array('uname' => pnUserGetVar('uname', $missatge['usuari']),
																		'sv' => $sv));
		$usersList .= $missatge['usuari'].'$$';
		if($missatge['adjunt'] != ''){
			// get file extension
			$fileExtension = strtolower(substr(strrchr($missatge['adjunt'],"."),1));
			// get file icon
			$ctypeArray = pnModFunc('iw_main', 'user', 'getMimetype', array('extension' => $fileExtension));
			$fileIcon = $ctypeArray['icon'];
		}
		$missatges[] = array('titol' => $missatge['titol'],
								'usuari' => $missatge['usuari'],
								'data' => date('d/m/y',$missatge['data']),
								'hora' => date('H.i', $missatge['data']),
								'fileIcon' => $fileIcon,
								'adjunt' => $missatge['adjunt'],
								'missatge' => $missatge['missatge'],
								'photo' => $photo);
		//set user as messages readed
		if (strpos($missatge['llegit'],'$'.pnUserGetVar('uid').'$')==0){
			$llegit = pnModApiFunc('iw_forums', 'user', 'llegit', array('fmid' => $missatge['fmid'],
																		'llegit' => $missatge['llegit']));
		}
	}
	//get all users information
	$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
	$users = pnModFunc('iw_main', 'user', 'getAllUsersInfo', array('sv' => $sv,
																	'info' => 'ncc',
																	'list' => $usersList));
	$pnRender->assign('users',$users);
	$pnRender->assign('missatges',$missatges);
	$pnRender->assign('fid',$fid);
	$pnRender -> assign('avatarsVisible', pnModGetVar('iw_forums','avatarsVisible'));
	$pnRender->assign('ftid',$ftid);
	return $pnRender->fetch('iw_forums_user_allmsg.htm');
}

/**
 * Delete a topic and all the messages contained in it
 * @author:   Albert Pï¿œrez Monfort (aperezm@xtec.cat)
 * @param:	the topic identity
 * @return:	Return user to topics list page
*/
function iw_forums_user_deltema($args)
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'REQUEST');
	$ftid = FormUtil::getPassedValue('ftid', isset($args['ftid']) ? $args['ftid'] : null, 'REQUEST');
	$confirmation = FormUtil::getPassedValue('confirmation', isset($args['confirmation']) ? $args['confirmation'] : null, 'POST');
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	// check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid));
	if($access < 4){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get forum information
	$forum = pnModAPIFunc('iw_forums', 'user', 'get', array('fid' => $fid));
	if($forum == false){
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));		
	}
	$tema = pnModAPIFunc('iw_forums', 'user', 'get_tema', array('ftid' => $ftid,
																'fid' => $fid));
   	if($tema == false){
		LogUtil::registerError (__('No messages have been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));	
	}
	if (empty($confirmation)) {
		// create output object
		$pnRender = pnRender::getInstance('iw_forums',false);
		$pnRender -> assign('name', $forum['nom_forum']);
		$pnRender -> assign('tema', $tema['titol']);
		$pnRender -> assign('ftid', $ftid);
		$pnRender -> assign('smoderator', $smoderator);
		$pnRender -> assign('fid', $fid);
		return $pnRender -> fetch('iw_forums_user_del_tema.htm');
	}
	// confirm authorisation code
	if (!SecurityUtil::confirmAuthKey('iw_forums')) {
		return LogUtil::registerAuthidError (pnModURL('iw_forums', 'user', 'forum', array('fid' => $fid,
																'ftid' => $ftid)));
	}
	// delete record
	if (pnModAPIFunc('iw_forums', 'user', 'deltema', array('fid' => $fid,
															'ftid' => $ftid))) {
        // deletion successful
		LogUtil::registerStatus (__('The topic has been deleted.', $dom));
    }
	// redirect user to forums table
	return pnRedirect(pnModURL('iw_forums', 'user', 'forum', array('fid' => $fid,
																	'ftid' => $ftid)));
}


/**
 * Change topic position
 * @author:   Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	the topic and forum identities
 * @return:	Return user to topics list page
*/
function iw_forums_user_order($args)
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'REQUEST');
	$ftid = FormUtil::getPassedValue('ftid', isset($args['ftid']) ? $args['ftid'] : null, 'REQUEST');
	$puts = FormUtil::getPassedValue('puts', isset($args['puts']) ? $args['puts'] : null, 'REQUEST');
	// Security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	//check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid));
	if($access < 4){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get forum information
	$registre = pnModAPIFunc('iw_forums', 'user', 'get', array('fid' => $fid));
	if($registre == false){
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));		
	}
	$tema = pnModAPIFunc('iw_forums','user','get_tema',array('ftid' => $ftid,
																'fid' => $fid));
   	if($tema == false){
		LogUtil::registerError (__('No messages have been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));	
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	$ordre = ($puts == '-1') ? $tema['order'] + 3 : $tema['order'] - 3;
	pnModAPIFunc('iw_forums', 'user', 'put_order', array('ftid' => $ftid,
															'ordre' => $ordre,
															'fid' => $fid));
	// reorder the topics
	pnModFunc('iw_forums', 'user', 'reorder', array('fid' => $fid));
	return pnRedirect(pnModURL('iw_forums', 'user', 'forum', array('fid' => $fid)));
}

/**
 * Reorder the topics into a forum
 * @author:   Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	the forum identity
 * @return:	Return user to topics list page
*/
function iw_forums_user_reorder($args)
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'REQUEST');
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	// get topics
	$temes = pnModAPIFunc('iw_forums', 'user', 'get_temes', array('fid' => $fid));
	if($temes == false){
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// reorder all elements with the values 0 2 4 6 8...
	foreach($temes as $tema){
		$i = $i + 2;	
		pnModAPIFunc('iw_forums', 'user', 'put_order', array('ftid' => $tema['ftid'],
																'ordre' => $i,
																'fid' => $fid));
	}
	// redirect user to forums list
	return pnRedirect(pnModURL('iw_forums', 'user', 'forum', array('fid' => $fid)));
}

/**
 * Delete the attached file in a message in edition mode
 * @author:   Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	the message main information
 * @return:	Return user to edit page
*/
function iw_forums_user_del_adjunt($args)
{
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'POST');
	$ftid = FormUtil::getPassedValue('ftid', isset($args['ftid']) ? $args['ftid'] : null, 'POST');
	$titol = FormUtil::getPassedValue('titol', isset($args['titol']) ? $args['titol'] : null, 'POST');
	$msg = FormUtil::getPassedValue('msg', isset($args['msg']) ? $args['msg'] : null, 'POST');
	$fmid = FormUtil::getPassedValue('fmid', isset($args['fmid']) ? $args['fmid'] : null, 'POST');
	$u = FormUtil::getPassedValue('u', isset($args['u']) ? $args['u'] : null, 'POST');
	$segur = FormUtil::getPassedValue('segur', isset($args['segur']) ? $args['segur'] : null, 'POST');
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	// check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid));
	if($access < 2){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// get forum information
	$registre = pnModAPIFunc('iw_forums', 'user', 'get', array('fid' => $fid));
	if($registre == false){
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn\'t been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));		
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	// get message information
	$dades_missatge = pnModAPIFunc('iw_forums', 'user', 'get_msg', array('fmid' => $fmid));
	if ($dades_missatge == false) {
		LogUtil::registerError (__('No messages have been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid));
	if($access < 2){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	// check if user is moderator and can edit the message
	$moderator = ($access == 4) ? true : false;
	if(!$moderator && (time() > $dades_missatge['data'] + 60 * $registre['msgDelTime'] || $dades_missatge['usuari'] != pnUserGetVar('uid'))){
		LogUtil::registerError (__('You can\'t access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));			
	}
	// get smarticons if module bbsmile is active
	if(pnModAvailable('bbsmile') && pnModIsHooked('bbsmile', 'iw_forums')){
		$icons = pnModAPIFunc('bbsmile', 'user', 'getall');
		$pnRender -> assign('icons', $icons);
	}else{
		$pnRender -> assign('icons', false);
	}
	//Procedim a fer l'esborrat del fitxer adjunt al missatge
	if($segur == 'on'){
		if(pnModAPIFunc('iw_forums', 'user', 'del_adjunt', array('fmid' => $fmid))){
			$dades_missatge['adjunt'] = '';
		}
	}
	$missatge = array('missatge' => $msg,
						'titol' => $titol,
						'fmid' => $fmid,
						'icon' => $dades_missatge['icon'],
						'adjunt' => $dades_missatge['adjunt']);
	$pnRender -> assign('fid', $fid);
	$pnRender -> assign('ftid', $ftid);
	$pnRender -> assign('missatge',$missatge);
	$pnRender -> assign('menu', $menu);
	$pnRender -> assign('adjunts', $registre['adjunts']);
	$pnRender -> assign('extensions', pnModGetVar('iw_main','extensions'));
	$pnRender -> assign('u', $u);
	return $pnRender -> fetch('iw_forums_user_edit_msg.htm');
}

/**
 * Generate a pager of messages
 * @author:   Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	the information needed for the pager
 * @return:	A pager navigator
*/
function iw_forums_user_pager($args){
	$dom = ZLanguage::getModuleDomain('iw_forums');
	$rpp = FormUtil::getPassedValue('rpp', isset($args['rpp']) ? $args['rpp'] : null, 'GET');
	$inici = FormUtil::getPassedValue('inici', isset($args['inici']) ? $args['inici'] : null, 'GET');
	$total = FormUtil::getPassedValue('total', isset($args['total']) ? $args['total'] : null, 'GET');
	$urltemplate = FormUtil::getPassedValue('urltemplate', isset($args['urltemplate']) ? $args['urltemplate'] : null, 'GET');
	// security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}
	// create output object
	$pnRender = pnRender::getInstance('iw_forums',false);
	// quick check to ensure that we have work to do
	if($total <= $rpp){
		return;
	}
	if(!isset($inici) || empty($inici)){
		$inici = 1;
	}
	if(!isset($rpp) || empty($rpp)){
		$rpp = 10;
	}
	// show startnum link
	if($inici != 1){
		$url = preg_replace('/%%/', 1, $urltemplate);
		$text = '<a href="'.$url.'"><<</a> | ';
	}else{
		$text = '<< | ';
	}
	$items[] = array('text' => $text);
	// show following items
	$pagenum = 1;
	for($curnum = 1; $curnum <= $total; $curnum += $rpp){
		if(($inici < $curnum) || ($inici > ($curnum + $rpp - 1))) {
			// mod by marsu - use sliding window for pagelinks
			if ((($pagenum % 10) == 0) // link if page is multiple of 10
					|| ($pagenum == 1) // link first page
					|| (($curnum >($inici - 4 * $rpp)) //link -3 and +3 pages
					&&($curnum <($inici + 4 * $rpp)))
			) {
				// Not on this page - show link
				$url = preg_replace('/%%/', $curnum, $urltemplate);
				$text = '<a href="' . $url.'">' . $pagenum . '</a> | ';
				$items[] = array('text' => $text);
			}
			//end mod by marsu
		}else{
			// on this page - show text
			$text = $pagenum.' | ';
			$items[] = array('text' => $text);
		}
		$pagenum++;
	}
	if(($curnum >= $rpp + 1) && ($inici < $curnum - $rpp)){
		$url = preg_replace('/%%/', $curnum - $rpp, $urltemplate);
		$text = '<a href="'.$url.'">>></a>';
	}else{
		$text = '>>';
	}
	$items[] = array('text' => $text);
	$pnRender -> assign('items', $items);
	return $pnRender -> fetch('iw_forums_user_pager.htm');
}

/**
 * Prepare the content of the forum to print it
 * @author:   Albert PÃ©rez Monfort (aperezm@xtec.cat)
 * @param:	the topic and the forum identities
 * @return:	A printable page
*/
/*
function iw_forums_user_printallmsg($args)
{
	$ftid = FormUtil::getPassedValue('ftid', isset($args['ftid']) ? $args['ftid'] : null, 'REQUEST');
	$fid = FormUtil::getPassedValue('fid', isset($args['fid']) ? $args['fid'] : null, 'REQUEST');
	$u = FormUtil::getPassedValue('u', isset($args['u']) ? $args['u'] : null, 'REQUEST');

	// Security check
	if (!SecurityUtil::checkPermission( 'iw_forums::', '::', ACCESS_READ)) {
		return LogUtil::registerPermissionError();
	}

	// Create output object
	$pnRender = pnRender::getInstance('iw_forums',false);



	//Carreguem la informaciï¿œ del fï¿œrum
	$forum = pnModAPIFunc('iw_forums', 'user','get', array('fid' => $fid));
	if ($forum == false) {
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn't been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}
	
	//check if user can access the forum
	$access = pnModFunc('iw_forums', 'user', 'access', array('fid' => $fid));
	if($access < 1){
		LogUtil::registerError (__('You can't access the forum', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}

	//Carreguem la informaciï¿œ dels missatges
	$missatges_llista = pnModAPIFunc('iw_forums', 'user', 'getall_msg', array('fid' => $fid,
												'ftid' => $ftid,
												'usuari' => $u,
												'indent' => 0,
												'idparent' => 0,
												'inici' => 1,
												'rpp' => 100000000));
	if($missatges_llista == false){
		LogUtil::registerError (__('The forum upon which the ation had to be carried out hasn't been found', $dom));
		return pnRedirect(pnModURL('iw_forums', 'user', 'main'));
	}

	//get all users information
	$sv = pnModFunc('iw_main', 'user', 'genSecurityValue');
	$usersInfo = pnModFunc('iw_main', 'user', 'getAllUsersInfo', array('sv' => $sv,
										'info' => 'ncc'));

	//tenim dades a l'agenda i construim el fitxer vcs
	//generem el fitxer on escriurem les dades a exportar
	$fitxer = pnModGetVar('iw_main','documentRoot').'/'.pnModGetVar('iw_forums','urladjunts').'/'.pnUserGetVar('uname').'.prt';
	$f = fopen($fitxer,'w');
	foreach($missatges_llista as $missatge){
		$missatges[] = array('titol' => $missatge['titol'],
					'usuari' => $usersInfo[$missatge['usuari']],
					'data' => date('d/m/y',$missatge['data']),
					'hora' => date('H.i',$missatge['data']),
					'adjunt' => $missatge['adjunt'],
					'missatge' => $missatge['missatge']);

		//Incorpodem a l'usuari com a llegit si es que no hi ï¿œs inclï¿œs
		if(strpos($missatge['llegit'],'$'.pnUserGetVar('uid').'$')==0){
			$llegit = pnModApiFunc('iw_forums', 'user', 'llegit', array('fmid' => $missatge['fmid'],
												'llegit' => $missatge['llegit']));
		}

		//Preparem la sortida per a la impressiï¿œ
		$printer = "<table width=100%>";
		$printer .= '<tr><td><font face=Arial color=navy><strong>'.$missatge['titol'].'</font></td></tr>';
		$printer .= '<tr><td>' . _FORUMSMSGDE . '<font face=Arial color=green><strong>' . $usersInfo[$missatge['usuari']] . '</strong></td></tr>';
		$printer .= '<tr><td>' . _FORUMSDATA . ': <font face=Arial size=2 color=696969><strong>' . date('d/m/y', $missatge['data']) . '</strong></font></td></tr>';
		$printer .= '<tr><td>' . _FORUMSHORA . ': <font face=Arial size=2 color=696969><strong>' . date('H.i',$missatge['data']) . '</strong></font></td></tr>';
		if($missatge['adjunt'] != ""){
			$printer .= '<tr><td>' . _FORUMSFITXERADJUNT . ': ' . $missatge['adjunt'] . '</td></tr>';
		}
		$printer .= '<tr><td><hr></td></tr>';
		$printer .= '<tr><td>' . pnModFunc('iw_forums', 'user', 'prepara_print', array('text' => $missatge['missatge'])) . '</td></tr>';
		$printer .= '<tr><td><hr></td></tr>';
		$printer .= "</table><br>";
		fwrite($f, $printer);
	}
	fclose($f);

	//Afegim el menï¿œ d'opcions d'un tema d'un fï¿œrum
	$pnRender -> assign('missatges',$missatges);
	$pnRender -> assign('printer',pnUserGetVar('uname'));
	$pnRender -> assign('error',__('An error has occurred while trying to print the messages. If the error prevails, get in touch with the administrator', $dom));
	return $pnRender -> fetch('iw_forums_user_printallmsg.htm');
}
*/
/**
 * Prepare text to printer
 * @author:   Albert Pï¿œrez Monfort (aperezm@xtec.cat)
 * @param:	the text that must to be prepared
 * @return:	The text prepared
*/
/*
function iw_forums_user_prepara_print($args){
	$text = FormUtil::getPassedValue('text', isset($args['text']) ? $args['text'] : null, 'REQUEST');

	// Substitueix l'apï¿œstof per '
	$text = str_replace("\r", '', str_replace('\'','ï¿œ',$text));
	// Substitueix l'apï¿œstof per "		
	$text = str_replace('"', '&quot;', $text);
	// Substitueix els salts de lï¿œnia per <br />
	$text = preg_replace('/(?<!>)\n/', "<br />", $text);
	return $text;
}
*/
