<?xml version = '1.0' encoding = 'UTF-8'?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:import="http://www.gencat.cat/educacio/sscc/correu" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:esb="http://www.oracle.com/esb/" xmlns:ws="http://www.example.com/webservice" xmlns:tns="http://www.gencat.cat/educacio/sscc/correu" targetNamespace="http://www.gencat.cat/educacio/sscc/correu">
    <import namespace="http://www.gencat.cat/educacio/sscc/correu" location="http://aplitic.xtec.cat:8080/esb/slide/ESB_Projects/._ESB-enviaCorreu/src/ESB-Correu.wsdl"/>
    
    <binding name="__esb_EnviaCorreu_Correu" type="tns:Correu">
        <esb:binding/>
        <operation name="enviament">
            <esb:operation event-name="ServeisComuns.intern.EnviaCorreu.a1.EnviaCorreu.enviament"/>
            <input/>
            <output/>
        </operation>
        <operation name="disponibilitat">
            <esb:operation event-name="ServeisComuns.intern.EnviaCorreu.a1.EnviaCorreu.disponibilitat"/>
            <input/>
            <output/>
        </operation>
    </binding>
    <binding name="__soap_EnviaCorreu_Correu" type="tns:Correu">
        <soap:binding xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="enviament">
            <soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" style="document" soapAction="enviament"/>
            <input>
                <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
            </input>
            <output>
                <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
            </output>
        </operation>
        <operation name="disponibilitat">
            <soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" style="document" soapAction="disponibilitat"/>
            <input>
                <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
            </input>
            <output>
                <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="ESB_EnviaCorreu_Service">
        <port name="__esb_EnviaCorreu_Correu" binding="tns:__esb_EnviaCorreu_Correu">
        </port>
        <port name="__soap_EnviaCorreu_Correu" binding="tns:__soap_EnviaCorreu_Correu">
            <soap:address xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" location="http://aplitic.xtec.cat:8080/event/ServeisComuns/intern/EnviaCorreu/a1/EnviaCorreu"/>
        </port>
    </service>
    <plt:partnerLinkType name="CorreuLT">
        <plt:role name="CorreuProvider">
            <plt:portType name="tns:Correu"/>
        </plt:role>
    </plt:partnerLinkType>
</definitions>