<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Strings for component 'filter_twitterwidget', language 'en', branch 'MOODLE_20_STABLE'
 *
 * @package   filter_twitterwidget
 * @copyright 1999 onwards Martin Dougiamas  {@link http://moodle.com}
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['filtername'] = 'Twitter Widget';
$string['twitterwidget_htmlnode'] = 'HTML node to wrap the HTML the widget generates';
$string['twitterwidget_htmlnode_config'] = 'This is the HTML node which will wrap around the HTML generated by the widget';
$string['twitterwidget_htmlnode_default'] = 'span';
